metadataPackage_1602884205764/objects/Application_Log__c.object
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Log</label>
        <referenceTo>Application_Log__c</referenceTo>
        <relationshipLabel>Application Logs</relationshipLabel>
        <relationshipName>Application_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/Communication_Configuration__c.object
<CustomObject>
    <label>Communication Configuration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communication Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadataPackage_1602884205764/classes/Omni_PrintServiceTest.cls
@isTest
private class Omni_PrintServiceTest {

    @isTest
    static void testFeedCreationForPrint() {
        Communication_Configuration__c config = TestDataFactory.createCommConfigForChannel('Fax');
        Case role = TestDataFactory.createClaimRole();
        List<Application_Log__c> appLogs = TestDataFactory.createApplicationLogs(TestDataFactory.TEST_SIZE_SMALL, true);
        Map<Omni_CommunicationDispatcher.RoleWithLog, Set<Communication_Configuration__c>> commConfigByRole = new Map<Omni_CommunicationDispatcher.RoleWithLog, Set<Communication_Configuration__c>>();
        commConfigByRole.put(new Omni_CommunicationDispatcher.RoleWithLog(appLogs[0], role), new Set<Communication_Configuration__c>{config});
        System.assertEquals(true,[SELECT Id FROM FeedItem].isEmpty(),'No FeedItem should exist');
        Test.startTest();
        Omni_PrintService printService = new Omni_PrintService(commConfigByRole);
        printService.handlePrint();
        Test.stopTest();
        System.assertEquals(false,[SELECT Id FROM FeedItem].isEmpty(),'FeedItem should be created');
    }
}