metadataPackage_1602884205764/objects/Application_Log__c.object
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Log</label>
        <referenceTo>Application_Log__c</referenceTo>
        <relationshipLabel>Application Logs</relationshipLabel>
        <relationshipName>Application_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/ExposureType__c.object
<CustomObject>
    <label>Exposure Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exposure Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>TypeCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>TypeCode</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/PolicyIssuingGroup__c.object
<CustomObject>
    <label>Policy Issuing Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>PolicyIssuingGroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Issuing Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>TypeCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>TypeCode</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/SurveyBuilder__c.object
<CustomObject>
    <label>Survey Builder</label>
    <nameField>
        <displayFormat>SB-{0000000000}</displayFormat>
        <label>SurveyBuilder Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Builder</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Adjustor_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Adjustor name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Broker_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Broker name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClaimForRole__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Claim for role SF Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClaimNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Claim number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Claim_LOB__c</fullName>
        <label>Claim lob</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AUC</fullName>
                    <label>Commercial Auto</label>
                </value>
                <value>
                    <fullName>EB</fullName>
                    <label>Commercial Property</label>
                </value>
                <value>
                    <fullName>AUP</fullName>
                    <label>Personal Auto</label>
                </value>
                <value>
                    <fullName>RE</fullName>
                    <label>Personal Property</label>
                </value>
                <value>
                    <fullName>SPY</fullName>
                    <label>Specialty Lines</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExposureForRole__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Exposure for role SF Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LiabilityConfirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Liability confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PartyContact__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Party contact SF Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Party_Address_Line__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Party address line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Party_City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Party city</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Party_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Party name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Party_Postal_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Party postal code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Party_Province__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Party province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIG_EN__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PIG EN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIG_FR__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PIG FR</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIG_Logo_EN__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PIG Logo EN</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>PIG_Logo_FR__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PIG Logo FR</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>PIG_Name_EN__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PIG Name EN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIG_Name_FR__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PIG Name FR</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProvinceOfIssuanceId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Province of issuance Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoleId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Role Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurveyLink__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Survey link</label>
        <type>Url</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/SurveyConfig__mdt.object
<CustomObject>
    <label>Survey Config</label>
    <pluralLabel>Survey Configs</pluralLabel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SendSurveyOnce__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Survey Once</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SurveyIndicatorAPIName__c</fullName>
        <label>Survey Indicator API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Claim</fullName>
                    <default>true</default>
                    <label>Claim</label>
                </value>
                <value>
                    <fullName>Exposure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

metadataPackage_1602884205764/classes/Omni_EOCSurveyRequestTest.cls
/**
* @description Test class for Omni_EOCSurveyRequest
* @author      Luis Merinero
* @date        09/03/2020                     
*/
@isTest
public class Omni_EOCSurveyRequestTest {
	
    @testSetup
    private static void testSetupData(){
        TestDataFactory.createExposureStatus();
        TestDataFactory.createContactTypeRole();
        TestDataFactory.createPolicyIssuingGroup();
        Case exposure = TestDataFactory.createOtherExposures(1)[0];
        Case role = TestDataFactory.createExposureRole(exposure);
        insert role;    
    }
    
	@isTest
    static void createAutoPropertySurvey(){
        Map<String,Omni_SurveyRequest> mapCaseConfig = new Map<String,Omni_SurveyRequest>();
        Case claim = [SELECT id, ClaimId__c, Policy_Issuing_Group__c FROM Case Where RecordType.Name  = 'Claim'];
        PolicyIssuingGroup__c issuingGroup = new PolicyIssuingGroup__c(TypeCode__c = 'intact');
        insert issuingGroup;
        claim.TotalLoss__c = 'PAR';
        claim.ClaimId__c = '123Claim';
        claim.Policy_Issuing_Group__c = issuingGroup.id;
        update claim;
        
        Case exposure = [SELECT id, ClaimId__c, RecordType.Name, ExposureId__c FROM Case Where RecordType.DeveloperName  = 'OtherExposure'];
        SurveyConfig__mdt autoConfig = [SELECT id, SurveyIndicatorAPIName__c, SendSurveyOnce__c, Type__c, Active__c FROM SurveyConfig__mdt WHERE SurveyIndicatorAPIName__c = 'SendAutoPropertySurvey__c'];
        Map<String, SurveyConfig__mdt> configMap = new Map<String, SurveyConfig__mdt>();
        configMap.put('SendAutoPropertySurvey__c',autoConfig);
        
        Omni_SurveyConfig request = new Omni_SurveyConfig(claim, null, null);
        request.surveyConfigByKey = configMap;
        Omni_SurveyRequest sRequest = new Omni_SurveyRequest(request);
        Map<String, Omni_SurveyRequest> surveyRequest = new Map<String, Omni_SurveyRequest>();
        surveyRequest.put(claim.ClaimId__c + '-Claim', sRequest);
        
        Test.startTest();
        System.enqueueJob(new Omni_EOCSurveyRequest(surveyRequest));
        Test.stopTest();
    }
    
	@isTest
    static void createBenefitsSurvey(){
        Map<String,Omni_SurveyRequest> mapCaseConfig = new Map<String,Omni_SurveyRequest>();
        Case claim = [SELECT id, ClaimId__c, Policy_Issuing_Group__c FROM Case Where RecordType.Name  = 'Claim'];
		PolicyIssuingGroup__c issuingGroup = new PolicyIssuingGroup__c(TypeCode__c = 'intact');
        insert issuingGroup;
        claim.TotalLoss__c = 'PAR';
        claim.ClaimId__c = '123Claim';
        claim.Policy_Issuing_Group__c = issuingGroup.id;
        update claim;
        
        Case exposure = [SELECT id, ClaimId__c, RecordType.Name, ExposureId__c FROM Case Where RecordType.DeveloperName  = 'OtherExposure'];
        exposure.RecordTypeId = Omni_ClaimEventConstant.RECORD_TYPE_ID_BENEFITS;
        exposure.ExposureId__c = '1234Exp';
        update exposure;
        
        Application_Log__c log = new Application_Log__c();
        insert log;
        
        SurveyConfig__mdt benefitsConfig = [SELECT id, SurveyIndicatorAPIName__c, SendSurveyOnce__c, Type__c, Active__c FROM SurveyConfig__mdt WHERE SurveyIndicatorAPIName__c = 'SendAutoPropertySurvey__c'];
        Map<String, SurveyConfig__mdt> configMap = new Map<String, SurveyConfig__mdt>();
        configMap.put('SendAccidentBenefitsSurvey__c',benefitsConfig);
        
        Omni_SurveyConfig request = new Omni_SurveyConfig(claim, exposure, log.id);
        request.surveyConfigByKey = configMap;
        
        Omni_SurveyRequest sRequest = new Omni_SurveyRequest(request);
        Map<String, Omni_SurveyRequest> surveyRequest = new Map<String, Omni_SurveyRequest>();
        surveyRequest.put(exposure.ExposureId__c + '-Exposure', sRequest);
        
        Test.startTest();
        System.enqueueJob(new Omni_EOCSurveyRequest(surveyRequest));
        Test.stopTest();
    }

    @isTest
    static void createAutoPropertySurveySync(){
        Map<String,Omni_SurveyRequest> mapCaseConfig = new Map<String,Omni_SurveyRequest>();
        Case claim = [SELECT id, ClaimId__c, Policy_Issuing_Group__c FROM Case Where RecordType.Name  = 'Claim'];
        PolicyIssuingGroup__c issuingGroup = new PolicyIssuingGroup__c(TypeCode__c = 'intact');
        insert issuingGroup;
        claim.TotalLoss__c = 'PAR';
        claim.ClaimId__c = '123Claim';
        claim.Policy_Issuing_Group__c = issuingGroup.id;
        update claim;
        
        Case exposure = [SELECT id, ClaimId__c, RecordType.Name, ExposureId__c FROM Case Where RecordType.DeveloperName  = 'OtherExposure'];
        SurveyConfig__mdt autoConfig = [SELECT id, SurveyIndicatorAPIName__c, SendSurveyOnce__c, Type__c, Active__c FROM SurveyConfig__mdt WHERE SurveyIndicatorAPIName__c = 'SendAutoPropertySurvey__c'];
        Map<String, SurveyConfig__mdt> configMap = new Map<String, SurveyConfig__mdt>();
        configMap.put('SendAutoPropertySurvey__c',autoConfig);
        
        Omni_SurveyConfig request = new Omni_SurveyConfig(claim, null, null);
        request.surveyConfigByKey = configMap;
        Omni_SurveyRequest sRequest = new Omni_SurveyRequest(request);
        Map<String, Omni_SurveyRequest> surveyRequest = new Map<String, Omni_SurveyRequest>();
        surveyRequest.put(claim.ClaimId__c + '-Claim', sRequest);
        
        Test.startTest();
        Omni_EOCSurveyServiceSync surveySerivce = new Omni_EOCSurveyServiceSync(surveyRequest);
        surveySerivce.createAndSendSurveys();
        Test.stopTest();
    }
    
	@isTest
    static void createBenefitsSurveySync(){
        Map<String,Omni_SurveyRequest> mapCaseConfig = new Map<String,Omni_SurveyRequest>();
        Case claim = [SELECT id, ClaimId__c, Policy_Issuing_Group__c FROM Case Where RecordType.Name  = 'Claim'];
		PolicyIssuingGroup__c issuingGroup = new PolicyIssuingGroup__c(TypeCode__c = 'intact');
        insert issuingGroup;
        claim.TotalLoss__c = 'PAR';
        claim.ClaimId__c = '123Claim';
        claim.Policy_Issuing_Group__c = issuingGroup.id;
        update claim;
        
        Case exposure = [SELECT id, ClaimId__c, RecordType.Name, ExposureId__c FROM Case Where RecordType.DeveloperName  = 'OtherExposure'];
        exposure.RecordTypeId = Omni_ClaimEventConstant.RECORD_TYPE_ID_BENEFITS;
        exposure.ExposureId__c = '1234Exp';
        update exposure;
        
        Application_Log__c log = new Application_Log__c();
        insert log;
        
        SurveyConfig__mdt benefitsConfig = [SELECT id, SurveyIndicatorAPIName__c, SendSurveyOnce__c, Type__c, Active__c FROM SurveyConfig__mdt WHERE SurveyIndicatorAPIName__c = 'SendAutoPropertySurvey__c'];
        Map<String, SurveyConfig__mdt> configMap = new Map<String, SurveyConfig__mdt>();
        configMap.put('SendAccidentBenefitsSurvey__c',benefitsConfig);
        
        Omni_SurveyConfig request = new Omni_SurveyConfig(claim, exposure, log.id);
        request.surveyConfigByKey = configMap;
        
        Omni_SurveyRequest sRequest = new Omni_SurveyRequest(request);
        Map<String, Omni_SurveyRequest> surveyRequest = new Map<String, Omni_SurveyRequest>();
        surveyRequest.put(exposure.ExposureId__c + '-Exposure', sRequest);
        
        Test.startTest();
        Omni_EOCSurveyServiceSync surveySerivce = new Omni_EOCSurveyServiceSync(surveyRequest);
        surveySerivce.createAndSendSurveys();
        Test.stopTest();
    }

    @isTest
    static void coverMethods() { 
        Map<String,Omni_SurveyRequest> mapCaseConfig = new Map<String,Omni_SurveyRequest>();
        Case claim = [SELECT id, ClaimId__c, Policy_Issuing_Group__c FROM Case Where RecordType.Name  = 'Claim'];
		PolicyIssuingGroup__c issuingGroup = new PolicyIssuingGroup__c(TypeCode__c = 'intact');
        insert issuingGroup;
        claim.TotalLoss__c = 'PAR';
        claim.ClaimId__c = '123Claim';
        claim.Policy_Issuing_Group__c = issuingGroup.id;
        update claim;
        
        Case exposure = [SELECT id, ClaimId__c, RecordType.Name, ExposureId__c, ExposureType__c FROM Case Where RecordType.DeveloperName  = 'OtherExposure'];
        exposure.RecordTypeId = Omni_ClaimEventConstant.RECORD_TYPE_ID_BENEFITS;
        exposure.ExposureId__c = '1234Exp';
        update exposure;

        Case role = [SELECT Id, RoleId__c, PIG_EN__c, PIG_Logo_EN__c, ClaimNumber__c, Adjustor_Name__c, Broker_Name__c, Claim_LOB__c, PIG_Name_EN__c, 
                        Party_Name__c, Party_Address_Line__c, Party_City__c, Party_Province__c, Party_Postal_Code__c, LiabilityConfirmed__c, 
                        ProvinceOfIssuanceId__c, PIG_FR__c, PIG_Logo_FR__c, PIG_Name_FR__c, ClaimForRole__c, ExposureForRole__c, PartyContact__c, 
                        PartyContact__r.FirstName, PartyContact__r.LastName, PartyContact__r.Email, PartyAccount__c, RoleNature__c, SurveyLink__c,
                        ExposureForRole__r.ExposureType__c
                     FROM Case 
                     WHERE ExposureForRole__c  = :exposure.Id];
        role.RoleId__c = '12345';
        Application_Log__c log = new Application_Log__c();
        insert log;
        
        SurveyConfig__mdt benefitsConfig = [SELECT id, SurveyIndicatorAPIName__c, SendSurveyOnce__c, Type__c, Active__c FROM SurveyConfig__mdt WHERE SurveyIndicatorAPIName__c = 'SendAutoPropertySurvey__c'];
        Map<String, SurveyConfig__mdt> configMap = new Map<String, SurveyConfig__mdt>();
        configMap.put('SendAccidentBenefitsSurvey__c',benefitsConfig);
        
        Omni_SurveyConfig request = new Omni_SurveyConfig(claim, exposure, log.id);
        request.surveyConfigByKey = configMap;
        
        Omni_SurveyRequest sRequest = new Omni_SurveyRequest(request);
        Map<String, Omni_SurveyRequest> surveyRequest = new Map<String, Omni_SurveyRequest>();
        surveyRequest.put(exposure.ExposureId__c + '-Exposure', sRequest);
        List<Omni_EOCSurveyRequest.MessageRequest> msgRequests = new List<Omni_EOCSurveyRequest.MessageRequest>{ 
                                                                        new Omni_EOCSurveyRequest.MessageRequest(
                                                                            EmailMessageTriggerHandlerHelper.SURVEY_TEMPLATS[0].Id,
                                                                            role,
                                                                            log.Id,
                                                                            null)
                                                                };
        Map<String, Omni_EOCSurveyRequest.MessageRequest> msgRequestByRoleId = new Map<String, Omni_EOCSurveyRequest.MessageRequest>{
                                                                                        role.RoleId__c => msgRequests[0]
                                                                                        };
        Test.startTest();
        Omni_EOCSurveyRequest req = new Omni_EOCSurveyRequest(surveyRequest);
        Map<String, Account> accountById = req.createAccounts(msgRequests);
        Map<String, Contact> contactById = req.createContacts(msgRequests, accountById);
        Map<String, SurveyBuilder__c> surveyBuildersByRoleId = req.createSurveyBuilders(
                                                                   msgRequests, 
                                                                   accountById,
                                                                   contactById);
        req.createTextFeeds(msgRequests, new List<Case>{exposure});
        req.createEmailMessages(msgRequestByRoleId, surveyBuildersByRoleId);
        req.updateRolesInRequests(msgRequestByRoleId);
        Test.stopTest();
    }

     @isTest
    static void coverMethodsSync() { 
        Map<String,Omni_SurveyRequest> mapCaseConfig = new Map<String,Omni_SurveyRequest>();
        Case claim = [SELECT id, ClaimId__c, Policy_Issuing_Group__c FROM Case Where RecordType.Name  = 'Claim'];
		PolicyIssuingGroup__c issuingGroup = new PolicyIssuingGroup__c(TypeCode__c = 'intact');
        insert issuingGroup;
        claim.TotalLoss__c = 'PAR';
        claim.ClaimId__c = '123Claim';
        claim.Policy_Issuing_Group__c = issuingGroup.id;
        update claim;
        
        Case exposure = [SELECT id, ClaimId__c, RecordType.Name, ExposureId__c, ExposureType__c FROM Case Where RecordType.DeveloperName  = 'OtherExposure'];
        exposure.RecordTypeId = Omni_ClaimEventConstant.RECORD_TYPE_ID_BENEFITS;
        exposure.ExposureId__c = '1234Exp';
        update exposure;

        Case role = [SELECT Id, RoleId__c, PIG_EN__c, PIG_Logo_EN__c, ClaimNumber__c, Adjustor_Name__c, Broker_Name__c, Claim_LOB__c, PIG_Name_EN__c, 
                        Party_Name__c, Party_Address_Line__c, Party_City__c, Party_Province__c, Party_Postal_Code__c, LiabilityConfirmed__c, 
                        ProvinceOfIssuanceId__c, PIG_FR__c, PIG_Logo_FR__c, PIG_Name_FR__c, ClaimForRole__c, ExposureForRole__c, PartyContact__c, 
                        PartyContact__r.FirstName, PartyContact__r.LastName, PartyContact__r.Email, PartyAccount__c, RoleNature__c, SurveyLink__c, 
                        ExposureForRole__r.ExposureType__c
                     FROM Case 
                     WHERE ExposureForRole__c  = :exposure.Id];
        role.RoleId__c = '12345';
        Application_Log__c log = new Application_Log__c();
        insert log;
        
        SurveyConfig__mdt benefitsConfig = [SELECT id, SurveyIndicatorAPIName__c, SendSurveyOnce__c, Type__c, Active__c FROM SurveyConfig__mdt WHERE SurveyIndicatorAPIName__c = 'SendAutoPropertySurvey__c'];
        Map<String, SurveyConfig__mdt> configMap = new Map<String, SurveyConfig__mdt>();
        configMap.put('SendAccidentBenefitsSurvey__c',benefitsConfig);
        
        Omni_SurveyConfig request = new Omni_SurveyConfig(claim, exposure, log.id);
        request.surveyConfigByKey = configMap;
        
        Omni_SurveyRequest sRequest = new Omni_SurveyRequest(request);
        Map<String, Omni_SurveyRequest> surveyRequest = new Map<String, Omni_SurveyRequest>();
        surveyRequest.put(exposure.ExposureId__c + '-Exposure', sRequest);
        List<Omni_EOCSurveyServiceSync.MessageRequest> msgRequests = new List<Omni_EOCSurveyServiceSync.MessageRequest>{ 
                                                                        new Omni_EOCSurveyServiceSync.MessageRequest(
                                                                            EmailMessageTriggerHandlerHelper.SURVEY_TEMPLATS[0].Id,
                                                                            role,
                                                                            log.Id,
                                                                            null)
                                                                };
        Map<String, Omni_EOCSurveyServiceSync.MessageRequest> msgRequestByRoleId = new Map<String, Omni_EOCSurveyServiceSync.MessageRequest>{
                                                                                        role.RoleId__c => msgRequests[0]
                                                                                        };
        Test.startTest();
        Omni_EOCSurveyServiceSync req = new Omni_EOCSurveyServiceSync(surveyRequest);
        Map<String, Account> accountById = req.createAccounts(msgRequests);
        Map<String, Contact> contactById = req.createContacts(msgRequests, accountById);
        Map<String, SurveyBuilder__c> surveyBuildersByRoleId = req.createSurveyBuilders(
                                                                   msgRequests, 
                                                                   accountById,
                                                                   contactById);
        req.createTextFeeds(msgRequests, new List<Case>{exposure});
        req.createEmailMessages(msgRequestByRoleId, surveyBuildersByRoleId);
        req.updateRolesInRequests(msgRequestByRoleId);
        Test.stopTest();
    }
}