metadataPackage_1602884205764/objects/Application_Log__c.object
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Log</label>
        <referenceTo>Application_Log__c</referenceTo>
        <relationshipLabel>Application Logs</relationshipLabel>
        <relationshipName>Application_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Exception</fullName>
                </value>
                <value>
                    <fullName>Integration</fullName>
                </value>
                <value>
                    <fullName>Auto Log</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description tied to the log. In the case of exception, it is the error message.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>The URL for the endpoint of the external service for the HTTP request</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Stack_Trace__c</fullName>
        <description>The stack trace of exception.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Exception Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Exception Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Type</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <description>The type of method used by HttpRequest.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Payload__c</fullName>
        <description>The body of the HTTP request.</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Request Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Payload__c</fullName>
        <description>The body returned in the HTTP response.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Response Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <description>Name of the source system making the inbound call into Salesforce.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Source System</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <description>The value of the status code returned in the response.</description>
        <label>Status Code</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Operation status.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Id__c</fullName>
        <description>The unique Id for every web service transaction with salesforce. For any inbound web service calls into salesforce , the Id should be provided by the external system. For any out bound calls from salesforce , this should be provided from salesforce.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Transaction Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Auto_Log</fullName>
        <active>true</active>
        <description>To store the log information for automatic notification process</description>
        <label>Auto Log</label>
    </recordTypes>
    <recordTypes>
        <fullName>ExceptionLog</fullName>
        <active>true</active>
        <label>Exception Log</label>
    </recordTypes>
    <recordTypes>
        <fullName>IntegrationLog</fullName>
        <active>true</active>
        <label>Integration Log</label>
    </recordTypes>
</CustomObject>

force-app/main/default/classes/ApplicationLog.cls
/**
* @author      Kejia Hu
* @date        2019-04-24
* @description model class for Application_Log__c
* <p>                                                                        
* 2019-04-24 - Kejia Hu - creation and inital commit                        
*/
public with sharing class ApplicationLog { 
    private enum statusEnum {Failure, Success}
    private String applicationName;
    private String category;
    private String description;
    private String endpoint;
    private String exceptionType;
    private String method;
    private String requestPayload;
    private String responsePayload;
    private String status;
    private Integer statusCode;
    private String transactionId;
    private String sourceSystem;
    private String integrationType;
    private String parentLogId;
    private Exception exceptionInst;
	private String logDesc;

    /**
    * @author      Kejia Hu
    * @date        2019-04-25
    * @param       String applicationName
    * @param       HttpRequest request
    * @param       HttpResponse response
    * @param       Exception e
    * @param       String sourceSystem
    * @param       String integrationType
    * @param       String parentLogId
    * @param       String transactionId
    * @description ApplicationLog consturctor
    */
    public ApplicationLog(String applicationName, HttpRequest request, HttpResponse response, Exception e, 
                            String sourceSystem, String integrationType, String parentLogId, String transactionId) {
        this.applicationName = applicationName;
        this.exceptionInst = e;
        this.sourceSystem = sourceSystem;
        this.integrationType = integrationType;
        this.parentLogId = parentLogId;
        this.transactionId = transactionId;
        this.status = (null == this.exceptionInst) ? this.status : statusEnum.Failure.Name();
        if (request != null) {
            this.method = request.getMethod();
            this.requestPayload = request.getBody();
            this.endpoint = request.getEndpoint();
            if (response != null) {
                this.responsePayload = response.getBody();
                Integer sc = response.getStatusCode();
                this.status = (sc < 300 && sc >= 100) ? statusEnum.Success.Name() : statusEnum.Failure.Name();
                this.statusCode = response.getStatusCode();
            } else {
                this.Status = statusEnum.Failure.Name();
                this.responsePayload = 'No Http Response';
            }
        }
    }
	
	/**
    * @author      Vikas Sharma
    * @date        2019-09-09
    * @param       String applicationName
    * @param	   String description
    * @param       HttpRequest request
    * @description ApplicationLog consturctor
    */
    public ApplicationLog(String applicationName,  String description, String parentLogId) {
        this.applicationName = applicationName;
        this.logDesc = description;
        this.parentLogId = parentLogId;
    }

    /**
    * @Description ApplicationLog consturctor
    * @Author      Kejia Hu
    * @Date        05/11/2019
    */
	public ApplicationLog(String applicationName,  String description, String parentLogId, String transactionId) {
        this.applicationName = applicationName;
        this.logDesc = description;
        this.parentLogId = parentLogId;
        this.transactionId = transactionId;
    }

    
    /**
    * @author      Kejia Hu
    * @date        2019-04-25
    * @return      Application_Log__c
    * @description persist an Application_Log__c record
    */
    public Application_Log__c save() {
        return persistApplicationLog(this);
    }
	
	/*public Application_Log__c saveAutoLogs() {
        return persistApplicationLog(this);
    }*/
	
    /**
    * @author      Kejia Hu
    * @date        2019-04-25
    * @param       ApplicationLog appLog
    * @return      Application_Log__c
    * @description persist an Application_Log__c record
    */
    public Application_Log__c persistApplicationLog(ApplicationLog appLog) {
        Application_Log__c logInst;
        logInst = createApplicationLog(appLog);
        if(null != logInst) {
            insert logInst;
        }
        return logInst;
    }

    /**
    * @author      Kejia Hu
    * @date        2019-04-25
    * @param       ApplicationLog appLog
    * @return      Application_Log__c
    * @description generate an Application_Log__c record from a instance of ApplicationLog
    *              check if the log is enabled before generating
    */
    public Application_Log__c createApplicationLog(ApplicationLog appLog) {
        Application_Log__c logInst;
        if(Utility.LOGGING_CONFIG.Exception_Logging_Enabled__c && null != appLog.exceptionInst) {
            logInst = new Application_Log__c();
            logInst.RecordTypeId = Utility.LOG_RECORD_TYPE_BY_APINAME.get('ExceptionLog');
            logInst.Application_Name__c = appLog.applicationName;
            logInst.Category__c = 'Exception';
            logInst.Description__c = appLog.exceptionInst.getMessage();
            logInst.Exception_Type__c = appLog.exceptionInst.getTypeName();
            logInst.Exception_Stack_Trace__c = appLog.exceptionInst.getStackTraceString();
            logInst.Status__c = appLog.status;
            logInst.Application_Log__c = appLog.parentLogId;
        }
        if(Utility.LOGGING_CONFIG.Integration_Logging_Enabled__c && null != appLog.requestPayload) {
            logInst = new Application_Log__c();
            logInst.Application_Name__c = appLog.applicationName;
            logInst.RecordTypeId = Utility.LOG_RECORD_TYPE_BY_APINAME.get('IntegrationLog');
            logInst.Category__c = 'Integration';
            logInst.Endpoint__c = Utility.truncateString(appLog.endpoint,
                                                Application_Log__c.Endpoint__c.getDescribe().getLength());
            logInst.Method__c = appLog.method;
            logInst.Request_Payload__c = Utility.truncateString(appLog.requestPayload,
                                                Application_Log__c.Request_Payload__c.getDescribe().getLength());
            logInst.Response_Payload__c = Utility.truncateString(appLog.responsePayload,
                                                Application_Log__c.Response_Payload__c.getDescribe().getLength());
            logInst.Status__c = appLog.status;
            logInst.Status_Code__c = appLog.statusCode;
            logInst.Integration_Type__c = appLog.integrationType;
            logInst.Source_System__c = appLog.sourceSystem;
            logInst.Transaction_Id__c = appLog.transactionId;
        }
        if (Omni_ClaimNotificationConstant.APP_NAME_PRINT_LOG == appLog.applicationName 
                || Omni_ClaimNotificationConstant.APP_NAME_FAX_LOG == appLog.applicationName
                || Omni_ClaimNotificationConstant.APP_NAME_EMAIL_LOG == appLog.applicationName) {
            logInst = new Application_Log__c();
            logInst.RecordTypeId = Utility.LOG_RECORD_TYPE_BY_APINAME.get('IntegrationLog');
            logInst.Application_Name__c = appLog.applicationName;
            logInst.Category__c = Omni_SMSConstant.SMS_EVENT_CATEGROY_INTEGRATION;
            logInst.Description__c = appLog.logDesc;
            logInst.Application_Log__c = appLog.parentLogId;
            logInst.Transaction_Id__c = appLog.transactionId; 
        }
		
		if(null != appLog.logDesc && 'Auto Log' == appLog.applicationName) {
            logInst = new Application_Log__c();
            logInst.RecordTypeId = Utility.LOG_RECORD_TYPE_BY_APINAME.get('Auto_Log');
            logInst.Application_Name__c = 'Auto Log';
            logInst.Category__c = 'Auto Log';
            logInst.Description__c = appLog.logDesc;
            logInst.Exception_Type__c =''; //appLog.exceptionInst.getTypeName();
            logInst.Exception_Stack_Trace__c = appLog.logDesc;//appLog.exceptionInst.getStackTraceString();
            logInst.Status__c = '';//appLog.status;
            logInst.Application_Log__c = appLog.parentLogId;
            
        }
        return logInst;
    }

    /**
    * @author      Kejia Hu
    * @date        2019-04-24
    * @description model class for Error message return to client                     
    */
    public class ExceptionData {
        String applicationName;
        String exceptionType;
        String description;
        String stackTrace;

        /**
        * @author      Kejia Hu
        * @date        2019-04-25
        * @param       ApplicationLog log
        * @description ExceptionDate consturctor
        */
        public ExceptionData(ApplicationLog log) {
            this.applicationName = log.applicationName;
            this.description = log.exceptionInst.getMessage();
            this.exceptionType = log.exceptionInst.getTypeName();
            this.stackTrace = log.exceptionInst.getStackTraceString();
        }
    }
}