metadataPackage_1602884205764/objects/Application_Log__c.object
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Log</label>
        <referenceTo>Application_Log__c</referenceTo>
        <relationshipLabel>Application Logs</relationshipLabel>
        <relationshipName>Application_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/File_Metadata__c.object
<CustomObject>
    <description>To store the metadata for the ECM files</description>
    <label>File Metadata</label>
    <nameField>
        <displayFormat>FM-{00000}</displayFormat>
        <label>File Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Sent_to_Handler__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Populated once the document is processed from the batch job</description>
        <label>Sent to Handler</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/classes/Omni_ECMRetrieveClassTest.cls
/**
* @description Test class for Omni_ECMRetrieveClass
* @author      Luis Merinero
* @date        05/03/2020                    
*/ 
@isTest
public class Omni_ECMRetrieveClassTest {

    @testSetup
    static void setup(){
        TestDataFactory.createECMConfiguration();
        insert new ContentVersion(VersionData = Blob.valueOf('ABCFileData'), Title = 'Test File', PathOnClient = 'Test File.jpg');
    }
    
    @isTest
    static void testECMRetrieveSuccess(){
        ContentVersion version = [SELECT id FROM ContentVersion LIMIT 1];
        Test.setMock(HttpCalloutMock.class, TestDataFactory.createServiceMock(200, '{"ecmDiscriminator": "CLM", "mimeType": "PDF", "slfid": "' + version.Id + '","trackingNumber": "123456ABC"}'));
        Test.startTest();
        Omni_AdhocFlowController.ECMRetrieveDocumentUrl('12345', 'http://cmpurl.com');
        Test.stopTest();
        File_Metadata__c fm = [SELECT id, Sent_to_Handler__c FROM File_Metadata__c LIMIT 1];
        System.assert(fm.Sent_to_Handler__c);
    }
    
	@isTest
    static void testECMRetrieveError(){
        Test.setMock(HttpCalloutMock.class, TestDataFactory.createServiceMock(200, '{"ecmDiscriminator": "CLM", "mimeType": "PDF", "slfid": "1234567","trackingNumber": "123456ABC"}'));
        Test.startTest();
        Omni_AdhocFlowController.ECMRetrieveDocumentUrl('12345', 'http://cmpurl.com');
        Test.stopTest();
        Application_Log__c[] logs = [SELECT id FROM Application_Log__c WHERE Application_Name__c = 'ECM Retrieve Request Exception'];
    	System.assertEquals(1, logs.size());
    }
}