metadataPackage_1602884205764/objects/Application_Log__c.object
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Log</label>
        <referenceTo>Application_Log__c</referenceTo>
        <relationshipLabel>Application Logs</relationshipLabel>
        <relationshipName>Application_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/File_Metadata__c.object
<CustomObject>
    <description>To store the metadata for the ECM files</description>
    <label>File Metadata</label>
    <nameField>
        <displayFormat>FM-{00000}</displayFormat>
        <label>File Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Document_Processing_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Document Processing Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MessageId__c</fullName>
        <description>Email Message SLF Id</description>
        <encryptionScheme>None</encryptionScheme>
        <label>MessageId</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <description>Reference Id : Lookup to the Content Version Id</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Unique Id</label>
        <length>254</length>
        <type>Text</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/Handler_Processed__e.object
<CustomObject>
    <description>Once handler receives the request to create metadata and it informs salesforce with this event</description>
    <label>Handler Processed</label>
    <pluralLabel>Handler Processed</pluralLabel>
    <fields>
        <fullName>MessageId__c</fullName>
        <label>MessageId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/classes/Omni_HandlerProcessedPETriggerTest.cls
@isTest
private class Omni_HandlerProcessedPETriggerTest {

    @isTest
    static void publishECMProcessedFailure(){
        File_Metadata__c fmetadataBefore = new File_Metadata__c(Reference_Id__c = '0684c0000000imlAAA', messageId__c = '06A4m0000000JRjEAB', Unique_Id__c = '06A4m0000000JRjEAB-0684c0000000imlAAA');
        insert fmetadataBefore;
        Test.startTest();
        Database.SaveResult sr = EventBus.publish(TestEventDataFactory.createHandlerProcessedEventFailure(
                                                    'c16bb02d-a36c-484f-8dca-b3c91e7447ae', '0684c0000000imlAAA', '06A4m0000000JRjEAB'));
        Test.stopTest();
        System.assertEquals(true, [SELECT Id From Application_Log__c].size()>0, 'Log should be created!');
        File_Metadata__c fmetadataAfter = [SELECT Id, Document_Processing_Status__c From File_Metadata__c WHERE Id = :fmetadataBefore.Id];
        System.assertEquals(true,fmetadataAfter.Document_Processing_Status__c.contains('Retrying'), 'Metadata status need to updated for Retrying');
    }

    @isTest
    static void publishECMProcessedSuccess(){
        File_Metadata__c fmetadataBefore = new File_Metadata__c(Reference_Id__c = '0684c0000000imlAAA', messageId__c = '06A4m0000000JRjEAM', Unique_Id__c = '06A4m0000000JRjEAB-0684c0000000imlAAA');
        insert fmetadataBefore;
        System.assertEquals(0, [SELECT Id From Application_Log__c].size(), 'No log should exist!');
        Test.startTest();
        Database.SaveResult sr = EventBus.publish(TestEventDataFactory.createHandlerProcessedEventSuccess(
                                                    'c16bb02d-a36c-484f-8dca-b3c91e7447ae', '0684c0000000imlAAA', '06A4m0000000JRjEAM'));
        Test.stopTest();
        System.assertEquals(true, [SELECT Id From Application_Log__c].size()>0, 'Log should be created!');
    }

    @isTest
    static void coverMethods() {
        Test.startTest();
        Omni_HandlerProcessedPETriggerHandler handler = new Omni_HandlerProcessedPETriggerHandler();
        handler.handleBeforeInsert(null);
        handler.handleBeforeUpdate(null,null);
        handler.handleBeforeDelete(null);
        handler.handleAfterUpdate(null,null);
        handler.handleAfterDelete(null);
        handler.handleAfterUndelete(null);
        Test.stopTest();
        System.assertEquals('Handler_Processed__e', handler.getObjectAPIName(),'Object name should be Handler_Processed__e');
    }

}