metadataPackage_1602884205764/objects/Application_Log__c.object
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Log</label>
        <referenceTo>Application_Log__c</referenceTo>
        <relationshipLabel>Application Logs</relationshipLabel>
        <relationshipName>Application_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Id__c</fullName>
        <description>The unique Id for every web service transaction with salesforce. For any inbound web service calls into salesforce , the Id should be provided by the external system. For any out bound calls from salesforce , this should be provided from salesforce.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Transaction Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/Omni_ApplicationLogSelector.cls
/**
* @Description: Selctor for Aplication Log sObject
* @Author:      Damian Kazior, PwC
* @Date:        30/09/2019
*/
public with sharing class Omni_ApplicationLogSelector {

    /**
    * @Description: Selctor for Aplication Log sObject
    * @Author:      Damian Kazior, PwC
    * @Date:        30/09/2019
    */
   public static Application_Log__c getApplicationLogById(String Id) {
       return [SELECT Transaction_Id__c FROM Application_Log__c WHERE Id =:Id];
    }

}