metadataPackage_1602884205764/objects/Application_Log__c.object
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Log</label>
        <referenceTo>Application_Log__c</referenceTo>
        <relationshipLabel>Application Logs</relationshipLabel>
        <relationshipName>Application_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Exception</fullName>
                </value>
                <value>
                    <fullName>Integration</fullName>
                </value>
                <value>
                    <fullName>Auto Log</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/Pulse_Survey_Result__c.object
<CustomObject>
    <label>Pulse Survey Result</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Purse Survey Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pulse Survey Results</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Purse_Survey_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Responded__c</fullName>
        <defaultValue>false</defaultValue>
        <description>boolean flag to check wether survey has a response</description>
        <label>Responded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Gold</fullName>
                    <label>Amazing</label>
                </value>
                <value>
                    <fullName>green</fullName>
                    <label>A</label>
                </value>
                <value>
                    <fullName>yellow</fullName>
                    <label>B</label>
                </value>
                <value>
                    <fullName>red</fullName>
                    <label>C</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

metadataPackage_1602884205764/classes/Omni_Aura_SurveyFormControllerTest.cls
/**
* @description Test class for Omni_Aura_SurveyFormController
* @author      Damian Kazior
* @date        29/01/2020                     
*/ 
@isTest
public class Omni_Aura_SurveyFormControllerTest {

    public static Case role;
    //public static Case claim;
    public static EmailMessage email;
    public static String testSurveyScore;
    public static final String SURVEY_IDENTIFIER = TestDataFactory.generateRandomNumber(10);

    @isTest
    private static void prepareData(){
         role                               = TestDataFactory.createClaimRole();
         email                              = TestDataFactory.createEmailMessages(1, role, false)[0]; 
         email.Pulse_Survey_Identifier__c   = SURVEY_IDENTIFIER;
         insert email;
         list<SelectOption>  
         surveyScoreOptions                 = getSurveyScoringOptions();
         testSurveyScore                    = surveyScoreOptions[0].getValue();
    }

    @isTest
    private static void updateSurveyResultsPositive(){

        String testComment;
        prepareData();
        Omni_AuraResponse auraResponse = Omni_Aura_SurveyFormController.validateSurvey(role.ClaimForRole__c, null, SURVEY_IDENTIFIER, testSurveyScore);
        Pulse_Survey_Result__c createdSurvey = [SELECT Id, Score__c, Responded__c FROM Pulse_Survey_Result__c][0]; 
        
        Omni_Aura_SurveyFormController.updateSurveyResults(createdSurvey.Id, testComment);
        createdSurvey = [SELECT Id, Score__c, Comments__c FROM Pulse_Survey_Result__c WHERE Id =: createdSurvey.Id][0]; 
        System.assertEquals(testComment, createdSurvey.Comments__c, 'Survey should have its comment'); 

        List<Application_Log__c> appLogs = [SELECT Id, Application_Name__c, Category__c
                                            FROM Application_Log__c
                                            WHERE Category__c = 'Exception'];
        System.assertEquals(0, appLogs.size(), 'Exception should not be created');
    }

    @isTest
    private static void updateSurveyResultsNegative(){

        Omni_Aura_SurveyFormController.updateSurveyResults(null, 'hi');
        
        List<Application_Log__c> appLogs = [SELECT Id, Application_Name__c, Category__c
                                            FROM Application_Log__c
                                            WHERE Category__c = 'Exception'];

        System.assertEquals(1, appLogs.size(), 'Exception must be created');
    }

    @isTest
    private static void validateSurveyPositive(){

        prepareData();
        Omni_AuraResponse auraResponse = Omni_Aura_SurveyFormController.validateSurvey(role.ClaimForRole__c, null, SURVEY_IDENTIFIER, testSurveyScore);
        System.assertEquals(true, auraResponse.success, 'Validation should pass'); 

        List<Pulse_Survey_Result__c> surveyResutls = [SELECT Id FROM Pulse_Survey_Result__c
                                                      WHERE Score__c =: testSurveyScore
                                                      AND Case__c =: role.ClaimForRole__c];
        System.assertEquals(1, surveyResutls.size(), 'One survey should be created');

        List<Application_Log__c> appLogs = [SELECT Id, Application_Name__c, Category__c
                                             FROM Application_Log__c
                                             WHERE Category__c = 'Exception'];
        System.assertEquals(0, appLogs.size(), 'Exception should not be created');
    }

    @isTest
    private static void createSurveyResultsNegative(){
        Omni_AuraResponse auraResponse = Omni_Aura_SurveyFormController.createSurveyResults(null, null, null);     
        System.assertEquals(auraResponse.success, false, 'invalid parameters should return error');
    }

    @isTest
    private static void validateSurveyNegative(){ 
        Omni_AuraResponse auraResponse = Omni_Aura_SurveyFormController.validateSurvey(null, null, null, null);    
        System.assertEquals(auraResponse.success, false, 'invalid parameters should return error');
    }


    private static List<SelectOption> getSurveyScoringOptions()
    {
        List<SelectOption> options = new List<SelectOption>();
                
        Schema.DescribeFieldResult fieldResult =
        Pulse_Survey_Result__c.Score__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
                
        for( Schema.PicklistEntry f : ple){
            options.add(new SelectOption(f.getValue(), f.getLabel()));
        }       
        return options;
    }



}