metadataPackage_1602884205764/objects/Application_Log__c.object
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Log</label>
        <referenceTo>Application_Log__c</referenceTo>
        <relationshipLabel>Application Logs</relationshipLabel>
        <relationshipName>Application_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/PolicyIssuingGroup__c.object
<CustomObject>
    <label>Policy Issuing Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>PolicyIssuingGroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Issuing Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>TypeCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>TypeCode</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/SurveyConfig__mdt.object
<CustomObject>
    <label>Survey Config</label>
    <pluralLabel>Survey Configs</pluralLabel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SendSurveyOnce__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Survey Once</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SurveyIndicatorAPIName__c</fullName>
        <label>Survey Indicator API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Claim</fullName>
                    <default>true</default>
                    <label>Claim</label>
                </value>
                <value>
                    <fullName>Exposure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/SurveyRequest__c.object
<CustomObject>
    <description>EOC Survey Requests, this object is used for failed EOC survey request re-sending</description>
    <label>Survey Request</label>
    <nameField>
        <displayFormat>SR-{0000000}</displayFormat>
        <label>Survey Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>JobId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Job Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PolicyIssuingGroup__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Policy Issuing Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalLoss__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Total Loss</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>SurveyRequest</fullName>
        <active>true</active>
        <label>Survey Request</label>
    </recordTypes>
</CustomObject>

force-app/main/default/classes/Omni_EOCSurveyRequestBatchTest.cls
@isTest
private class Omni_EOCSurveyRequestBatchTest {

    @testSetup
    private static void testSetupData(){
        TestDataFactory.createExposureStatus();
        TestDataFactory.createContactTypeRole();
        TestDataFactory.createPolicyIssuingGroup();
        Case exposure = TestDataFactory.createOtherExposures(1)[0];
        Case role = TestDataFactory.createExposureRole(exposure);
        insert role;    
    }
    
	@isTest
    static void runScheduleSurveyBatch(){
        Map<String,Omni_SurveyRequest> mapCaseConfig = new Map<String,Omni_SurveyRequest>();
        Case claim = [SELECT id, ClaimId__c, Policy_Issuing_Group__c FROM Case Where RecordType.Name  = 'Claim'];
		PolicyIssuingGroup__c issuingGroup = new PolicyIssuingGroup__c(TypeCode__c = 'intact');
        insert issuingGroup;
        claim.TotalLoss__c = 'PAR';
        claim.ClaimId__c = '123Claim';
        claim.Policy_Issuing_Group__c = issuingGroup.id;
        update claim;
        
        Case exposure = [SELECT id, ClaimId__c, RecordType.Name, ExposureId__c FROM Case Where RecordType.DeveloperName  = 'OtherExposure'];
        exposure.RecordTypeId = Omni_ClaimEventConstant.RECORD_TYPE_ID_BENEFITS;
        exposure.ExposureId__c = '1234Exp';
        update exposure;
        
        Application_Log__c log = new Application_Log__c();
        insert log;
        
        SurveyConfig__mdt benefitsConfig = [SELECT id, SurveyIndicatorAPIName__c, SendSurveyOnce__c, Type__c, Active__c FROM SurveyConfig__mdt WHERE SurveyIndicatorAPIName__c = 'SendAutoPropertySurvey__c'];
        Map<String, SurveyConfig__mdt> configMap = new Map<String, SurveyConfig__mdt>();
        configMap.put('SendAccidentBenefitsSurvey__c',benefitsConfig);
        
        Omni_SurveyConfig request = new Omni_SurveyConfig(claim, exposure, log.id);
        request.surveyConfigByKey = configMap;
        
        Omni_SurveyRequest sRequest = new Omni_SurveyRequest(request);
        Map<String, Omni_SurveyRequest> surveyRequest = new Map<String, Omni_SurveyRequest>();
        surveyRequest.put(exposure.ExposureId__c + '-Exposure', sRequest);

        String jobId = System.enqueueJob(new Omni_EOCSurveyRequest(surveyRequest));
        Omni_ClaimEventHelper.saveEOCRequests(surveyRequest, jobId);
        System.assertEquals(false, [SELECT Id FROM SurveyRequest__c WHERE JobId__c = :jobId].isEmpty(), 'survey requests should be created');
        
        Test.startTest();
        Omni_EOCSurveyRequestBatchSchedule schedulableClass = new Omni_EOCSurveyRequestBatchSchedule();
        schedulableClass.execute(null);
        Test.stopTest();
        System.assertEquals(true, [SELECT Id FROM SurveyRequest__c WHERE JobId__c = :jobId].isEmpty(), 'survey requests should be deleted after batch job');
    }

}