metadataPackage_1602884205764/objects/Application_Log__c.object
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Log</label>
        <referenceTo>Application_Log__c</referenceTo>
        <relationshipLabel>Application Logs</relationshipLabel>
        <relationshipName>Application_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>ExceptionLog</fullName>
        <active>true</active>
        <label>Exception Log</label>
    </recordTypes>
    <recordTypes>
        <fullName>IntegrationLog</fullName>
        <active>true</active>
        <label>Integration Log</label>
    </recordTypes>
</CustomObject>

metadataPackage_1602884205764/objects/ECM_Metadata__c.object
<CustomObject>
    <label>ECM Metadata</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>ECM Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ECM Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>File_Metadata__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>File Metadata</label>
        <referenceTo>File_Metadata__c</referenceTo>
        <relationshipLabel>ECM Metadata</relationshipLabel>
        <relationshipName>ECM_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/File_Metadata__c.object
<CustomObject>
    <description>To store the metadata for the ECM files</description>
    <label>File Metadata</label>
    <nameField>
        <displayFormat>FM-{00000}</displayFormat>
        <label>File Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Claim_Number__c</fullName>
        <description>Claim number from Case object</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Claim Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <description>Count of files - Its always zero unless its a zip ( populated by the handler)</description>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>File_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked once file ( Content Document) is deleted from the salesforce - We are not deleting the metadata, only binary is deleted(Content Document)</description>
        <label>File Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>File_Mime_Type__c</fullName>
        <description>File type - Not exact Mime type but the file type - Populate it from Content Version</description>
        <encryptionScheme>None</encryptionScheme>
        <label>File Mime Type</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processed_by_ECM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked once ECM has finished processing the document ( updated the ECM Id)</description>
        <label>Processed by ECM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <description>Reference Id : Lookup to the Content Version Id</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>254</length>
        <type>Text</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/classes/BatchDeleteECMProcessedDocs.cls
/**
* @description Batch Class to delete  ECM processed Documents. It will pick up the 
File_Metadata__c and send it to Handler
* @author      Vikas Sharma
* @date        15/01/2020                     
*/

global class BatchDeleteECMProcessedDocs implements Database.Batchable<sObject>, Database.AllowsCallouts{
    
    private String query;
    public static Application_Log__c integrationLog;
    public static String error {get; private set;}
    public  boolean isMockTest = false;
    List<String> listOfSFIds = new List<String>();
    
    global BatchDeleteECMProcessedDocs(Boolean isQA, List<String> listOfSFIds){
        this.isMockTest = isQA;
        this.listOfSFIds = listOfSFIds;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        query = 'SELECT Id, Reference_Id__c,File_Mime_Type__c, Count__c FROM File_Metadata__c WHERE Processed_by_ECM__c = true AND File_Deleted__c = false';
        if (isMockTest)
        {
            query = 'SELECT Id, Reference_Id__c,File_Mime_Type__c,Count__c FROM File_Metadata__c WHERE Name in: listOfSFIds AND Processed_by_ECM__c = true  AND File_Deleted__c = false';
        }
        return Database.getQueryLocator(query);
        
    }
    global void execute(Database.BatchableContext BC, List<File_Metadata__c> scope){
	Application_Log__c integrationLog;
        integrationLog = ApplicationLogHandler.createIntegrationLogs('', '','Success', '','', 'Delete Batch ECM Docs');
        insert integrationLog;
	try{		
        Set<Id> contentVersionIds = new Set<Id>();
        List<ContentDocument> contentDocumentsToDelete = new List<ContentDocument>();
        List<File_Metadata__c> toUpdateFileMetadata = new List<File_Metadata__c>();
        
        Map<Id, Decimal> contentVersionCountMap = new Map<Id,Decimal>();
        
        for (File_Metadata__c  fMeta : scope){
			contentVersionCountMap.put(fMeta.Id,fMeta.Count__c);
        }
        contentVersionIds.addAll(compareCountAndECMMetadata(contentVersionCountMap));
        contentVersionIds = removeFilesPendingProcess(contentVersionIds);
        
        for (ContentVersion currentContentVersion : [SELECT ContentDocumentId ,Id from ContentVersion 
                                                Where Id in: contentVersionIds 
                                               ]){
            contentDocumentsToDelete.add(new ContentDocument(Id = currentContentVersion.ContentDocumentId));
        }
        deleteContentDocuments(contentDocumentsToDelete, integrationLog);
        updateFileMetadata(contentVersionIds);    
        }
        catch(Exception e){
         	Application_Log__c exceptionLog;	
            exceptionLog = ApplicationLogHandler.saveExceptionLog('ECM Delete Batch Request Exception', e, integrationLog.Id);
        }
    }
    
    private void updateFileMetadata (Set<Id> contentVersionIds){
        List<File_Metadata__c> toDelete = new List<File_Metadata__c>();
        
        for (File_MetaData__c fileMetadata : [SELECT Id, File_Deleted__c FROM File_Metadata__c
                                              Where Reference_Id__c in : contentVersionIds]){
        	toDelete.add(new File_Metadata__c(Id = fileMetadata.Id, 
                                               File_Deleted__c = true ));    
        }
        update toDelete;
    }
    
    // to popluate the list of files to delete if 
    // file type is zipped
     private Set<Id> compareCountAndECMMetadata(Map<Id, Decimal> fileMetadataCount){
         Set<Id> toReturn = new Set<Id>();
         Map<Id, List<String>> ecmCounts = new Map<Id, List<String>>();
         Map<Id,Id> metaContentMap = new Map<Id,Id>();
         for(ECM_Metadata__c ecmMetadata : [SELECT Id,File_Metadata__c, File_Metadata__r.Reference_Id__c FROM ECM_Metadata__c 
                                            WHERE File_Metadata__c in : fileMetadataCount.keyset()]){
             metaContentMap.put(ecmMetadata.File_Metadata__c, ecmMetadata.File_Metadata__r.Reference_Id__c);
             if (ecmCounts.get(ecmMetadata.File_Metadata__c) == null){
                 ecmCounts.put(ecmMetadata.File_Metadata__c, new List<String>{ecmMetadata.Id});
             }
             else{
                 ecmCounts.get(ecmMetadata.File_Metadata__c).add(ecmMetadata.Id);
             }
         }
         
         for(Id currentFileMetadata : fileMetadataCount.keyset()){
             decimal currentCount = fileMetadataCount.get(currentFileMetadata);
         	if (ecmCounts.get(currentFileMetadata) != null &&
                ecmCounts.get(currentFileMetadata).size() >= currentCount){
                toReturn.add(metaContentMap.get(currentFileMetadata));
            }
         }
         return toReturn;
	}
    
    private Set<Id> removeFilesPendingProcess(Set<Id> contentVersionIds){
        for(File_Metadata__c fileMetadata : [SELECT id, Reference_Id__c FROM File_Metadata__c 
                                             WHERE Processed_By_ECM__c = false 
                                             AND Claim_Number__c != null
                                             AND Reference_Id__c IN :contentVersionIds]){
            if(contentVersionIds.contains(fileMetadata.Reference_Id__c)){
				contentVersionIds.remove(fileMetadata.Reference_Id__c);
            }
        }
        return contentVersionIds;
    }
    
    private static void deleteContentDocuments(List<ContentDocument> toDelete, Application_Log__c integrationLog){
        Database.DeleteResult[] drList = Database.delete(toDelete, false);
        // Iterate through each returned result
        for(Database.DeleteResult dr : drList) {
            if (!dr.isSuccess()) {
                // Operation failed, Log Erros               
                for(Database.Error err : dr.getErrors()) {
                    BatchECMDocumentDeleteException e = new BatchECMDocumentDeleteException(err.getMessage());
					ApplicationLogHandler.saveExceptionLog('ECM Delete Batch Request Exception', e, integrationLog.Id);
                }
            }
        }
        //delete toDelete;
    }
    
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }
	public class BatchECMDocumentDeleteException extends Exception {}	
}