metadataPackage_1602884205764/objects/Application_Log__c.object
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Log</label>
        <referenceTo>Application_Log__c</referenceTo>
        <relationshipLabel>Application Logs</relationshipLabel>
        <relationshipName>Application_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>The URL for the endpoint of the external service for the HTTP request</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>IntegrationLog</fullName>
        <active>true</active>
        <label>Integration Log</label>
    </recordTypes>
</CustomObject>

metadataPackage_1602884205764/objects/Ecm_Composition__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Ecm Composition</label>
    <fields>
        <fullName>Endpoint__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oauth_ClientId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Oauth ClientId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oauth_Scope__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Oauth Scope</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oauth_Secret__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Oauth Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oauth_Token_Url__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Oauth Token Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/ECM_Metadata__c.object
<CustomObject>
    <label>ECM Metadata</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>ECM Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ECM Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>CMP_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CMP Id</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ECM_File_Mime_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ECM File Mime Type</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ECM_File_Size__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ECM File Size</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ECM__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ECM File Title</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Metadata__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>File Metadata</label>
        <referenceTo>File_Metadata__c</referenceTo>
        <relationshipLabel>ECM Metadata</relationshipLabel>
        <relationshipName>ECM_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/File_Metadata__c.object
<CustomObject>
    <description>To store the metadata for the ECM files</description>
    <label>File Metadata</label>
    <nameField>
        <displayFormat>FM-{00000}</displayFormat>
        <label>File Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Count__c</fullName>
        <description>Count of files - Its always zero unless its a zip ( populated by the handler)</description>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Document_Title__c</fullName>
        <description>The title of the Document - Populate it from Email Message object</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Document Title</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked once file ( Content Document) is deleted from the salesforce - We are not deleting the metadata, only binary is deleted(Content Document)</description>
        <label>File Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>File_Mime_Type__c</fullName>
        <description>File type - Not exact Mime type but the file type - Populate it from Content Version</description>
        <encryptionScheme>None</encryptionScheme>
        <label>File Mime Type</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Size__c</fullName>
        <description>Size of the file  - Populate it from Content Version</description>
        <label>File Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Processed_by_ECM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked once ECM has finished processing the document ( updated the ECM Id)</description>
        <label>Processed by ECM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <description>Reference Id : Lookup to the Content Version Id</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sent_to_Handler__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Populated once the document is processed from the batch job</description>
        <label>Sent to Handler</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/default/classes/Omni_ECMRetrieveClass.cls
public without sharing class Omni_ECMRetrieveClass {
    public static String error {get; private set;}
    public static Application_Log__c integrationLog;
    
    public static String invoke(String cmpid, String cmpUrl) {
        ServiceResponse serviceResponse = new ServiceResponse();
        String contentVersionId;
        
        try {
			//Obtain oAuth Token
            Ecm_Composition__c ecm = Ecm_Composition__c.getOrgDefaults();
            String access_token = getToken(ecm);
            
            HttpRequest req = new HttpRequest();
            req.setEndpoint(ecm.Endpoint__c + 'v1/retrieveDocument');
            req.setMethod('POST');
            req.setTimeout(120000);
			req.setHeader('Content-Type', 'application/json');
			req.setHeader('Accept', 'application/json');	
            req.setHeader('Authorization', 'Bearer ' + access_token);
            
            String transactionId = Omni_Utils.NewGuid();
            ServiceRequest serviceRequest = makeRequest(cmpUrl, transactionId);
            String body = JSON.serialize(serviceRequest, true);
            req.setBody(body);
            
            Http http = new Http();
            HttpResponse httpResponse = http.send(req);
            
            integrationLog = ApplicationLogHandler.saveOutboundIntegrationLog('ECM Retrieve Request', req, httpResponse, transactionId);
            
            serviceResponse = (ServiceResponse)JSON.deserialize(httpResponse.getBody(), ServiceResponse.class);
            contentVersionId = serviceResponse.slfId;
            ContentVersion versionRecord = Omni_ContentVersionSelector.getContentDocumentIdFromContentVersionId(contentVersionId);
            if(versionRecord.Id != null){
                ContentDocumentLink cdLink = new ContentDocumentLink(ContentDocumentId = versionRecord.ContentDocumentId, LinkedEntityId = UserInfo.getUserId());
                Database.insert(cdLink, false);
                upsertMetadata(versionRecord.Id, cmpid);
                return versionRecord.ContentDocumentId;
           	}else{
                error = 'ContentDocumentId not found. ContentVersionId provided: ' + contentVersionId;
                throw new Omni_ECMSearchClassException(error);
            }
        }  catch (exception e) {
			if(integrationLog != null){
          		ApplicationLogHandler.saveExceptionLog('ECM Retrieve Request Exception', e, integrationLog.Id);
            }else{
                ApplicationLogHandler.saveExceptionLog('ECM Retrieve Request Exception', e, null);
            }
        }
        return null;
    }
    
    private static ServiceRequest makeRequest(String cmpUrl, String transactionId) {
        ServiceRequest serviceRequest = new ServiceRequest();
        
        serviceRequest.cmpUrl = cmpUrl;
        serviceRequest.ecmDiscriminator = 'CLM';
        serviceRequest.trackingNumber = transactionId;
        serviceRequest.requestor = 'SLFC';

        return serviceRequest;
    }
    
    public static void upsertMetadata(Id versionId, String cmpid){
        update new ContentVersion(id = versionId, CmpId__c = cmpid);
        
		File_Metadata__c[] fileMetadata = [SELECT id, File_Mime_Type__c, File_Size__c, Document_Title__c
                                         FROM File_Metadata__c WHERE Reference_Id__c = :versionId LIMIT 1];
        
        if(fileMetadata.size()>0){
            fileMetadata[0].Processed_by_ECM__c = true; 
            fileMetadata[0].Sent_to_Handler__c = true;
            fileMetadata[0].File_Deleted__c = false;
            fileMetadata[0].Count__c = 1;
            
            Update fileMetadata[0];
            
            insert new ECM_Metadata__c(CMP_Id__c = cmpid,
                                       File_Metadata__c = fileMetadata[0].Id, 
                                       ECM_File_Mime_Type__c = fileMetadata[0].File_Mime_Type__c,
                                       ECM_File_Size__c	= String.valueOf(fileMetadata[0].File_Size__c),
                                       ECM__c = fileMetadata[0].Document_Title__c);
        }
    }
	
    //Obtain Access Token
    Private Static String getToken(Ecm_Composition__c ecm){
        String tokenRequestBody = 'grant_type=client_credentials&client_id=' + ecm.Oauth_ClientId__c + '&client_secret=' + ecm.Oauth_Secret__c + '&scope=' + ecm.Oauth_Scope__c;
        
        HttpRequest accessTokenReq = new HttpRequest();
        accessTokenReq.setEndpoint(ecm.Oauth_Token_Url__c);
        accessTokenReq.setMethod('POST');
        accessTokenReq.setBody(tokenRequestBody);
        
        Http accessTokenHttp = new Http();
        HTTPResponse accessTokenResponse = accessTokenHttp.send(accessTokenReq);
        token_oauth tokenResponse =  (token_oauth)JSON.deserialize(accessTokenResponse.getBody(), token_oauth.Class);
        return tokenResponse.access_token; 
    }
    
    public class ServiceRequest {
        public String cmpUrl;
        public String ecmDiscriminator;
        public String trackingNumber;
        public String requestor;
    }
    
    public class ServiceResponse {
        public String ecmDiscriminator;
        public String mimeType;
        public String slfId;
        public String trackingNumber;
    }
    
	public class token_oauth{
        public string access_token;
        public string scope;
        public string token_type;
        public Integer expires_in;
    }
    
    public class Omni_ECMSearchClassException extends Exception {}	
}