metadataPackage_1602884205764/objects/Application_Log__c.object
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Log</label>
        <referenceTo>Application_Log__c</referenceTo>
        <relationshipLabel>Application Logs</relationshipLabel>
        <relationshipName>Application_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description tied to the log. In the case of exception, it is the error message.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exception_Stack_Trace__c</fullName>
        <description>The stack trace of exception.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Exception Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/Pulse_Survey_Result__c.object
<CustomObject>
    <label>Pulse Survey Result</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Purse Survey Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pulse Survey Results</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Purse_Survey_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Gold</fullName>
                    <label>Amazing</label>
                </value>
                <value>
                    <fullName>green</fullName>
                    <label>A</label>
                </value>
                <value>
                    <fullName>yellow</fullName>
                    <label>B</label>
                </value>
                <value>
                    <fullName>red</fullName>
                    <label>C</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/Omni_TaskGeneratorTest.cls
/**
* @description Test class for Omni_TaskGenerator
* @author      Damian Kazior
* @date        29/01/2020                     
*/ 
@isTest 
public without sharing class Omni_TaskGeneratorTest {

    public static Case parentCase;
    public static List<EmailMessage> emailMessages;

    @isTest
    private static void prepareData(){
        parentCase              = TestDataFactory.createClaim();
        List<Case> tasks = [select id, ownerId from Case where id=:parentCase.Id];
        emailMessages           = TestDataFactory.createEmailMessages(TestDataFactory.TEST_SIZE_SMALL, parentCase, true);
        TestDataFactory.createPulseSurveyResult(TestDataFactory.TEST_SIZE_SMALL, parentCase, Omni_TaskGenerator.PULSE_BAD_SCORE, true);

    }

    @isTest
    private static void createTaskForEmailPositive(){ 

        prepareData(); 
        Test.startTest();
        insert emailMessages;
        Test.stopTest();

        List<Task> tasks = [select Id, whatId, ownerid from Task WHERE RecordtypeId =: Omni_TaskGenerator.RECORD_TYPE_ID_EMAIL];
        System.assertEquals(TestDataFactory.TEST_SIZE_SMALL, tasks.size(), 'There must be one task per each emailmessage');
        List<Application_Log__c> appLogs = [SELECT Id from Application_Log__c];
        System.assertEquals(0, appLogs.size(), 'No exception should have been thrown');
    }

    @isTest
    private static void createTaskForSurveyPositive(){

        prepareData(); 
        List<Pulse_Survey_Result__c> pulseSurveyResults = [SELECT Id, Score__c, OwnerId FROM Pulse_Survey_Result__c WHERE Case__c =:parentCase.Id];
        List<Task> tasks = [select Id, whatId, ownerid from Task WHERE RecordtypeId =: Omni_TaskGenerator.RECORD_TYPE_ID_SURVEY];
        
        System.assertEquals(pulseSurveyResults.size(), tasks.size(), 'There must be one task per each survey');
        List<Application_Log__c> appLogs = [SELECT Id , Description__c,Exception_Stack_Trace__c from Application_Log__c];
        System.assertEquals(0, appLogs.size(), 'No exception should have been thrown');
    }

    @isTest
    private static void createTaskForMatchedDEAEmailTest(){

        prepareData(); 
        Omni_TaskGenerator.createTaskForMatchedDEAEmail(parentCase, emailMessages);
    }

    @isTest
    private static void createTaskForDEAEmailTest(){

        prepareData(); 
        Omni_EmailProcessingEntity entity = new Omni_EmailProcessingEntity('test');
        entity.masterCase = parentCase;
        List<Omni_EmailProcessingEntity> emailMessageEntites = new List<Omni_EmailProcessingEntity>();
        emailMessageEntites.add(entity);
        Omni_TaskGenerator.createTaskForMatchedDEAEmail(emailMessageEntites);

    }

}