metadataPackage_1602884205764/objects/Application_Log__c.object
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Log</label>
        <referenceTo>Application_Log__c</referenceTo>
        <relationshipLabel>Application Logs</relationshipLabel>
        <relationshipName>Application_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Exception</fullName>
                </value>
                <value>
                    <fullName>Integration</fullName>
                </value>
                <value>
                    <fullName>Auto Log</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

metadataPackage_1602884205764/classes/PurgeExceptionLogScheduleTest.cls
@isTest
private class PurgeExceptionLogScheduleTest {

    @isTest
    static void runPurgeExceptionLogSchedule(){
        Integer logNumForEach = 20;
        List<Application_Log__c> appLogs = TestDataFactory.createExceptionIntegrationAppLogs(logNumForEach);
        for(Application_Log__c log : appLogs){
            Test.setCreatedDate(log.Id, DateTime.newInstance(2018,01,01));
        }
        System.assertequals(logNumForEach, [SELECT Id FROM Application_Log__c WHERE Category__c = 'Exception'].size());
        Test.startTest();
        String jobId = System.schedule('Purge Exception Logs', '0 1 * * * ?', new PurgeExceptionLogSchedule());
        Test.stopTest();
        List<CronTrigger> ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        System.assertEquals(1, ct.size(), 'new job should be scheduled');
    }
}