metadataPackage_1602884205764/objects/Application_Log__c.object
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AdditionalPayload__c</fullName>
        <description>holds additional payload if the payload size beyond the text area maximum characters</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Additional Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Application_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Log</label>
        <referenceTo>Application_Log__c</referenceTo>
        <relationshipLabel>Application Logs</relationshipLabel>
        <relationshipName>Application_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Exception</fullName>
                </value>
                <value>
                    <fullName>Integration</fullName>
                </value>
                <value>
                    <fullName>Auto Log</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReferenceNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Reference Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Payload__c</fullName>
        <description>The body of the HTTP request.</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Request Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Operation status.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrackingNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tracking Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Id__c</fullName>
        <description>The unique Id for every web service transaction with salesforce. For any inbound web service calls into salesforce , the Id should be provided by the external system. For any out bound calls from salesforce , this should be provided from salesforce.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Transaction Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>ExceptionLog</fullName>
        <active>true</active>
        <label>Exception Log</label>
    </recordTypes>
    <recordTypes>
        <fullName>IntegrationLog</fullName>
        <active>true</active>
        <label>Integration Log</label>
    </recordTypes>
</CustomObject>

metadataPackage_1602884205764/objects/File_Metadata__c.object
<CustomObject>
    <description>To store the metadata for the ECM files</description>
    <label>File Metadata</label>
    <nameField>
        <displayFormat>FM-{00000}</displayFormat>
        <label>File Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Document_Processing_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Document Processing Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Handler_ECM_Failure__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Handler/ECM Failed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MessageId__c</fullName>
        <description>Email Message SLF Id</description>
        <encryptionScheme>None</encryptionScheme>
        <label>MessageId</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sent_to_Handler__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Populated once the document is processed from the batch job</description>
        <label>Sent to Handler</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Unique Id</label>
        <length>254</length>
        <type>Text</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/Handler_Processed__e.object
<CustomObject>
    <description>Once handler receives the request to create metadata and it informs salesforce with this event</description>
    <label>Handler Processed</label>
    <pluralLabel>Handler Processed</pluralLabel>
    <fields>
        <fullName>LifeCycle_Status__c</fullName>
        <label>LifeCycle Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MessageId__c</fullName>
        <label>MessageId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFId__c</fullName>
        <description>Salesforce Id of the document processed</description>
        <label>SFId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the request</description>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrackingId__c</fullName>
        <description>The transaction or tracking Id linked with every request</description>
        <label>TrackingId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/HandlerProcessedTriggerHandlerHelper.cls
/**
* @description Helper class for HandlerProcessedTriggerHandler
* @author      Vikas Sharma
* @date        13/01/2020                     
*/
public class HandlerProcessedTriggerHandlerHelper {
    
	public static String SF_RETRY_EXCEPTIONS = System.Label.eCM_Ingest_Retry_Status;
    
    /**
    * @description Update the Flag on File Metadata
    * 			   
    * @author      Vikas Sharma
    * @date        13/01/2020                     
    */
    public static void updateTheFlagForFileMetadata(Map<String, sObject> mapOfDocumentList)
    {
        List<File_Metadata__c> toUpdate = new List<File_Metadata__c>();
        Map<String, Application_Log__c> integrationLogByTransId = new Map<String, Application_Log__c>();
        Map<String,String> UniqueIdsMap = new Map<String,String>();
        String transactionIds;
        Application_Log__c integrationLog = new Application_Log__c();
        
        try{
            for (String currentId : mapOfDocumentList.keySet()){
                Application_Log__c integrationLogPerEvent;
                
                Handler_Processed__e handlerProcessedEvent = (Handler_Processed__e)mapOfDocumentList.get(currentId);
                integrationLogPerEvent = generateIntegrationLog(handlerProcessedEvent, Omni_ClaimNotificationConstant.LOG_STATUS_PROCESSED);
                integrationLogByTransId.put(handlerProcessedEvent.TrackingId__c, integrationLogPerEvent);
                transactionIds += handlerProcessedEvent.TrackingId__c + '; ';
                
                if (handlerProcessedEvent.Status__c == 'Failure'){
                    String UniqueId = handlerProcessedEvent.messageId__c + '-' + handlerProcessedEvent.SFId__c;
                	UniqueIdsMap.put(UniqueId, handlerProcessedEvent.LifeCycle_Status__c);
                }
            }
            for (File_Metadata__c fileMetadata : [SELECT Id, Unique_Id__c FROM File_Metadata__c WHERE Unique_Id__c in :UniqueIdsMap.KeySet()]){
                if(SF_RETRY_EXCEPTIONS.contains(UniqueIdsMap.get(fileMetadata.Unique_Id__c))){
                    String retryProcessingStatus = 'Retrying - ' + UniqueIdsMap.get(fileMetadata.Unique_Id__c);
					toUpdate.add(new File_Metadata__c (Id = fileMetadata.Id, Sent_to_Handler__c = false, 
                                                      Document_Processing_Status__c = retryProcessingStatus));
                }else{
                    toUpdate.add(new File_Metadata__c (Id = fileMetadata.Id, Handler_ECM_Failure__c = true,
                                                       Document_Processing_Status__c = UniqueIdsMap.get(fileMetadata.Unique_Id__c)));
                }
            }
            if (!integrationLogByTransId.isEmpty()) {
                insert integrationLogByTransId.values();
                integrationLog = integrationLogByTransId.values()[0];
            }
            update toUpdate;
        }
        catch(Exception e)
        {
            Application_Log__c exceptionLog = ApplicationLogHandler.saveExceptionLog('Handler Processed Bulk exception'
                                                                                     , new HandlerProcessedTriggerHandlerException(e.getMessage()+'.\n Transaction Ids are: '+transactionIds, e)
                                                                                     ,'');   
        }
    }
    
    public static Application_Log__c generateIntegrationLog(Handler_Processed__e notifEvent, String status) {
        String payloadBody = JSON.serialize(notifEvent);
        String transIdForLog = notifEvent.TrackingId__c;
        Application_Log__c integrationLog = genereateIntegrationLog(payloadBody, transIdForLog, status, '', '');
        return integrationLog;
    }
    
    public static Application_Log__c genereateIntegrationLog(String payload, String transactionId, String status, String referenceNum, String TrackingNum) {
        Application_Log__c eventLog = new Application_Log__c();
        eventLog.RecordTypeId = Utility.LOG_RECORD_TYPE_BY_APINAME.get('IntegrationLog');
        eventLog.Application_Name__c = 'Handler Processed Platform Event';
        eventLog.Category__c = 'Integration';
        eventLog.Transaction_Id__c = transactionId;
        eventLog.Status__c = status;
        eventLog.ReferenceNumber__c = referenceNum;
        eventLog.TrackingNumber__c = TrackingNum;
        if (payload.length()>131072) {
            eventLog.Request_Payload__c =  payload.substring(0, 131071);
            eventLog.AdditionalPayload__c = (payload.substring(131072).length()>131072)
                ? payload.substring(131072).substring(0, 131071)
                : payload.substring(131072);
        } else {
            eventLog.Request_Payload__c =  payload;
        }
        return eventLog;
    }
    public class HandlerProcessedTriggerHandlerException extends Exception {}
}