metadataPackage_1602884205764/objects/Communication_Configuration__c.object
<CustomObject>
    <label>Communication Configuration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communication Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Communication_Type__c</fullName>
        <label>Communication Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Custom Criteria</fullName>
                </value>
                <value>
                    <fullName>EMAIL</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Print</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Custom_Criteria__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Custom Criteria</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eligibility_Criteria__c</fullName>
        <description>To check the eligibility criteria of selected role</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Eligibility Criteria</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Explicit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Explicit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exposure_Type__c</fullName>
        <label>Exposure Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AutoDamage</fullName>
                </value>
                <value>
                    <fullName>BusinessInt</fullName>
                    <label>Business Interruption</label>
                </value>
                <value>
                    <fullName>EmployerLiability</fullName>
                    <label>Employer Liability</label>
                </value>
                <value>
                    <fullName>LossOfUse</fullName>
                </value>
                <value>
                    <fullName>PersonalPropertyDamage</fullName>
                </value>
                <value>
                    <fullName>vehicle</fullName>
                </value>
                <value>
                    <fullName>LivingExp</fullName>
                </value>
                <value>
                    <fullName>building</fullName>
                </value>
                <value>
                    <fullName>Contents</fullName>
                </value>
                <value>
                    <fullName>benefits</fullName>
                </value>
                <value>
                    <fullName>Crime</fullName>
                </value>
                <value>
                    <fullName>Equipment</fullName>
                </value>
                <value>
                    <fullName>BoilerMach</fullName>
                </value>
                <value>
                    <fullName>PropertyDamage</fullName>
                </value>
                <value>
                    <fullName>cargo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fax_Subject_EN__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Fax Subject EN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fax_Subject_FR__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Fax Subject FR</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Print_Subject_EN__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Print Subject EN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Print_Subject_FR__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Print Subject FR</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>insured</fullName>
                </value>
                <value>
                    <fullName>test</fullName>
                    <label>Test</label>
                </value>
                <value>
                    <fullName>driver</fullName>
                </value>
                <value>
                    <fullName>CommunicationContact</fullName>
                </value>
                <value>
                    <fullName>maincontact</fullName>
                </value>
                <value>
                    <fullName>reporter</fullName>
                </value>
                <value>
                    <fullName>claimant</fullName>
                </value>
                <value>
                    <fullName>agent</fullName>
                </value>
                <value>
                    <fullName>custodian</fullName>
                </value>
                <value>
                    <fullName>ExtLegalRepSF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SMS_Subject_EN__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SMS Subject EN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMS_Subject_FR__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SMS Subject FR</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/Language_Config__c.object
<CustomObject>
    <label>Language Config</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Language Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Language Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Communication_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to Communication Configuration</description>
        <label>Communication Configuration</label>
        <referenceTo>Communication_Configuration__c</referenceTo>
        <relationshipLabel>Language Configs</relationshipLabel>
        <relationshipName>Language_Configs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_Template__c</fullName>
        <description>Email template name to send emails</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Email Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language_Qualifier__c</fullName>
        <description>API name of field to check on Roles for qualification</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Language_Qualifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMS_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SMS Template</label>
        <referenceTo>SMS_Template__c</referenceTo>
        <relationshipLabel>Language Configs</relationshipLabel>
        <relationshipName>Language_Configs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/SMS_Template__c.object
<CustomObject>
    <label>SMS Template</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SMS Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Message__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

force-app/main/default/classes/Omni_ConfigurationSelector.cls
/**
* @Description: Selctor for Configuration sObject
* @Author:      Vikas Sharma
* @Date:        21/08/2019
*/
public with sharing class Omni_ConfigurationSelector {
    
    
    /**
* @description retrieve Configurations associated with Event Names
* @author      Vikas Sharma
* @date        21/08/2019                     
*/
    public static Map<String, List<Communication_Configuration__c>> getConfigurationsByEventNames(Set<String> eventNames) {
        Map<String, List<Communication_Configuration__c>> eventNamesWithConfigurations = new Map<String, List<Communication_Configuration__c>>();
        List<Communication_Configuration__c> configurations = [SELECT EventName__c, Communication_Type__c, Name,Custom_Criteria__c,
                                                               Role__c,Exposure_Type__c,Eligibility_Criteria__c,SMS_Subject_EN__c,
                                                               SMS_Subject_FR__c,Fax_Subject_EN__c,
                                                               Fax_Subject_FR__c, Print_Subject_EN__c,
                                                               Print_Subject_FR__c,Explicit__c
                                                               FROM Communication_Configuration__c 
                                                               WHERE EventName__c in:  eventNames
                                                               AND Active__c = true
                                                              ];
        if (!configurations.isEmpty()) {
            for(Communication_Configuration__c config : configurations) {
                if (eventNamesWithConfigurations.get(config.EventName__c) == null){
                    eventNamesWithConfigurations.put(config.EventName__c, new List<Communication_Configuration__c>{config});
                }
                else
                {
                    eventNamesWithConfigurations.get(config.EventName__c).add(config);
                }
            }
        }
        return eventNamesWithConfigurations;
    }
    
    /**
* @description retrieve Configurations associated with Event Names
* @author      Vikas Sharma
* @date        21/08/2019                     
*/
    public static Set<String> getAllConfigurations() {
        Set<String> toReturn = new Set<String>();
        
        for (Communication_Configuration__c config : [SELECT EventName__c, Communication_Type__c,
                                                      Name,Custom_Criteria__c,Explicit__c, 
                                                      Role__c,Exposure_Type__c,Eligibility_Criteria__c
                                                      FROM Communication_Configuration__c 
                                                      WHERE Eligibility_Criteria__c  != null
                                                      AND Active__c = true])       
        {
            toReturn.add(config.Eligibility_Criteria__c);
            
            if (config.Custom_Criteria__c != null)
            {
                toReturn.add(config.Custom_Criteria__c);	   
            }
        }
        
        return toReturn;
    }
    /**
* @description retrieve Configurations associated with Event Names
* @author      Vikas Sharma
* @date        21/08/2019                     
*/
    public static Map<String, Id> getEmailTemplatesId(Set<String> eventNames) {
        
        Map<String, Id> toReturn = new Map<String, Id>();
        List<String> listOfTemplates = new List<String>();
        
        /*for (Communication_Configuration__c config : [SELECT TemplateName__c
                                                      FROM Communication_Configuration__c 
                                                      WHERE EventName__c in:  eventNames
                                                     ])
        {
            listOfTemplates.add(config.TemplateName__c);
        }*/
        
        for (Language_Config__c langConfig : [SELECT Email_Template__c FROM Language_Config__c
                                             	WHERE Communication_Configuration__r.EventName__c in : eventNames
                                                AND Active__c = true])
        {
            listOfTemplates.add(langConfig.Email_Template__c);
        }
        for (EmailTemplate template : [SELECT Name, DeveloperName, Id from EmailTemplate 
                                       WHERE DeveloperName in : listOfTemplates 
                                      ])
        {
            toReturn.put(template.DeveloperName, template.Id);
        }
        return toReturn;
    }
    
    
    /**
* @description:  To retrieve the list of all language configurations
* 				Currently only fetching configurations for current event names
* @author      Vikas Sharma
* @date        10/09/2019                     
*/
    public static Map<Id, List<Language_Config__c>> getLanguageConfigurations(Set<String> eventNames) {
        
        Map<Id, List<Language_Config__c>> toReturn = new Map<Id, List<Language_Config__c>>();
        List<Id> configIds = new List<Id>();
        
        for (Communication_Configuration__c config : [SELECT Id
                                                      FROM Communication_Configuration__c 
                                                      WHERE EventName__c in:  eventNames
                                                      AND Active__c = true
                                                     ])
        {
            configIds.add(config.Id);
        }
        
        
        for (Language_Config__c langConfig : [SELECT Communication_Configuration__c	, Email_Template__c,
                                              Language_Qualifier__c, SMS_Template__r.Message__c ,Id
                                              FROM Language_Config__c 
                                              WHERE Communication_Configuration__c in : configIds
                                              AND Active__c = true 
                                             ])
        {
            if (toReturn.get(langConfig.Communication_Configuration__c) == null)
            {
                toReturn.put(langConfig.Communication_Configuration__c, new List<Language_Config__c>{langConfig});
            }
            else{
                toReturn.get(langConfig.Communication_Configuration__c).add(langConfig);
            }
            
        }
        return toReturn;
    }   
    
    /**
* @description:  To retrieve the list of all language configurations
* 				Currently only fetching configurations for current event names
* @author      Vikas Sharma
* @date        10/09/2019                     
*/
    public static Set<String> getFieldNamesFromLanguageConfig() {
        Set<String> toReturn = new Set<String>();
        
        for (Language_Config__c config : [SELECT Communication_Configuration__c	, Email_Template__c, 
                                                      Language_Qualifier__c, SMS_Template__c ,Id
                                                      FROM Language_Config__c 
                                                      WHERE Language_Qualifier__c != null
                                                      AND Active__c = true])       
        {
            toReturn.add(config.Language_Qualifier__c);	                                                  
        }
        
        return toReturn;
    }
}