metadataPackage_1602884205764/objects/Communication_Configuration__c.object
<CustomObject>
    <label>Communication Configuration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communication Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadataPackage_1602884205764/objects/LiveMessage__c.object
<CustomObject>
    <label>LiveMessage</label>
    <nameField>
        <displayFormat>SMS-{0000000}</displayFormat>
        <label>LiveMessages Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LiveMessages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>LiveMessages</relationshipLabel>
        <relationshipName>LiveMessages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Communication_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Communication Configuration</label>
        <referenceTo>Communication_Configuration__c</referenceTo>
        <relationshipLabel>LiveMessages</relationshipLabel>
        <relationshipName>LiveMessages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exposure_For_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exposure For Role</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>LiveMessages (Exposure For Role)</relationshipLabel>
        <relationshipName>LiveMessages1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message_Text__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Message Text</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Parent_Integration_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Integration Log</label>
        <referenceTo>Application_Log__c</referenceTo>
        <relationshipLabel>LiveMessages</relationshipLabel>
        <relationshipName>LiveMessages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Phone Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Name__c</fullName>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Recipient Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/Omni_SMSUtilities.cls
public with sharing class Omni_SMSUtilities {

    /**
    * @description Wrapper class to store data for one SMS payload. This sms payload might potenitally be broken down 
                   into multiple messages if it's length is too large. 
    * @author      Damian Kazior, PwC
    * @date        2019-09-18                 
    */
    public static Omni_SMSService.SMSDataWrapper createSMSDataWrapperFromLivemessage(LiveMessage__c liveMessage){
        
        Omni_SMSService.SMSDataWrapper smsData = new Omni_SMSService.SMSDataWrapper();
        smsData.cas                    = liveMessage.Case__r; 
        smsData.liveMessage            = liveMessage;
        smsData.smsTemplate            = liveMessage.Message_Text__c; 
        smsData.phoneNumber            = liveMessage.Phone_Number__c;
        smsData.recipientName          = liveMessage.Recipient_Name__c;
        smsData.exposureForRole        = liveMessage.Exposure_For_Role__r;
        smsData.communicationConfig    = liveMessage.Communication_Configuration__r;
        smsData.parentIntegrationLogId = liveMessage.Parent_Integration_Log__c;
        return smsData;
    }

}