metadataPackage_1602884205764/objects/Communication_Configuration__c.object
<CustomObject>
    <label>Communication Configuration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communication Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>SMS_Subject_EN__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SMS Subject EN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMS_Subject_FR__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SMS Subject FR</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/ExposureType__c.object
<CustomObject>
    <label>Exposure Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exposure Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadataPackage_1602884205764/objects/LiveMessage__c.object
<CustomObject>
    <label>LiveMessage</label>
    <nameField>
        <displayFormat>SMS-{0000000}</displayFormat>
        <label>LiveMessages Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LiveMessages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>LiveMessages</relationshipLabel>
        <relationshipName>LiveMessages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Claim_For_Role__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Claim For Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Communication_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Communication Configuration</label>
        <referenceTo>Communication_Configuration__c</referenceTo>
        <relationshipLabel>LiveMessages</relationshipLabel>
        <relationshipName>LiveMessages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exposure_For_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exposure For Role</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>LiveMessages (Exposure For Role)</relationshipLabel>
        <relationshipName>LiveMessages1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exposure_Type_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Exposure Type Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message_Text__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Message Text</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Parent_Integration_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Integration Log</label>
        <referenceTo>Application_Log__c</referenceTo>
        <relationshipLabel>LiveMessages</relationshipLabel>
        <relationshipName>LiveMessages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Phone Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Name__c</fullName>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Recipient Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Delievered</fullName>
                    <label>Delivered</label>
                </value>
                <value>
                    <fullName>Undelivered</fullName>
                </value>
                <value>
                    <fullName>Retried</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

metadataPackage_1602884205764/classes/Omni_LiveMessageSelector.cls
/**
 * @Description: Selector for LiveMessage sObject
 * @author:      Damian Kazior, PwC
 * @Date:        2019-09-24
 */
public without sharing class Omni_LiveMessageSelector {

    public static List<LiveMessage__c> getLiveMessagesByIds(List<String> ids){ 
        return [SELECT Case__c, Case__r.ExposureForRole__c,Case__r.PartyAccount__c, Case__r.ExposureForRole__r.ExposureType__c,
                Case__r.ClaimForRole__c,  Message_Text__c, Phone_Number__c, Status__c,
                Case__r.RecordTypeId, Case__r.ClaimForExposure__c, Case__r.ExposureType__c,
                Recipient_Name__c, Exposure_For_Role__r.ExposureType__c,     
                Claim_For_Role__c, Exposure_Type_Id__c, Communication_Configuration__r.SMS_Subject_EN__c, 
                Communication_Configuration__r.SMS_Subject_FR__c, Parent_Integration_Log__c
                FROM LiveMessage__c 
                WHERE Id IN : ids];
    } 

    public static LiveMessage__c getLiveMessageById(String id){ 
        List<String> ids = new List<String>();
        ids.add(id);
        return getLiveMessagesByIds(ids)[0];
    } 
}