metadataPackage_1602884205764/objects/ECM_Metadata__c.object
<CustomObject>
    <label>ECM Metadata</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>ECM Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ECM Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>CMP_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CMP Id</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ECM_File_Mime_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ECM File Mime Type</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ECM_File_Size__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ECM File Size</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eCM_File_URL__c</fullName>
        <formula>IF(ISBLANK(CMP_Id__c),&quot;&quot;,$Label.Omni_ECMLink +  CMP_Id__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>eCM File URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ECM__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ECM File Title</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Metadata__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>File Metadata</label>
        <referenceTo>File_Metadata__c</referenceTo>
        <relationshipLabel>ECM Metadata</relationshipLabel>
        <relationshipName>ECM_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/File_Metadata__c.object
<CustomObject>
    <description>To store the metadata for the ECM files</description>
    <label>File Metadata</label>
    <nameField>
        <displayFormat>FM-{00000}</displayFormat>
        <label>File Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Meta_Junction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meta Junction</label>
        <referenceTo>Meta_Junction__c</referenceTo>
        <relationshipLabel>File Metadata</relationshipLabel>
        <relationshipName>File_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/Meta_Junction__c.object
<CustomObject>
    <description>To store the information link between email message and File Metadata</description>
    <label>Meta Junction</label>
    <nameField>
        <displayFormat>MJ-{00000}</displayFormat>
        <label>Meta Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meta Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadataPackage_1602884205764/classes/Omni_ECMMetadataSelector.cls
/**
* @Description: Selctor for ECM_Metadata__c sObject
* @Author:      Luis Merinero
* @Date:        03/02/2020
*/
public class Omni_ECMMetadataSelector {
    
	/**
	* @description Retrieve Adhoc Shadow Role Cases related to the exposure
    * @author      Luis Merinero
    * @date        30/01/2020                    
    */
    public static List<ECM_Metadata__c> getECMMetadataByEmailMessage(String metaJunctionId){
        System.debug(metaJunctionId);
        return [SELECT id, ECM__c, CMP_Id__c, ECM_File_Mime_Type__c, ECM_File_Size__c, eCM_File_URL__c
                FROM ECM_Metadata__c WHERE File_Metadata__r.Meta_Junction__c = :metaJunctionId];
    }

}