metadataPackage_1602884205764/objects/ECM_Metadata__c.object
<CustomObject>
    <label>ECM Metadata</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>ECM Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ECM Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>File_Metadata__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>File Metadata</label>
        <referenceTo>File_Metadata__c</referenceTo>
        <relationshipLabel>ECM Metadata</relationshipLabel>
        <relationshipName>ECM_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/File_Metadata__c.object
<CustomObject>
    <description>To store the metadata for the ECM files</description>
    <label>File Metadata</label>
    <nameField>
        <displayFormat>FM-{00000}</displayFormat>
        <label>File Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Count__c</fullName>
        <description>Count of files - Its always zero unless its a zip ( populated by the handler)</description>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>File_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked once file ( Content Document) is deleted from the salesforce - We are not deleting the metadata, only binary is deleted(Content Document)</description>
        <label>File Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>File_Mime_Type__c</fullName>
        <description>File type - Not exact Mime type but the file type - Populate it from Content Version</description>
        <encryptionScheme>None</encryptionScheme>
        <label>File Mime Type</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processed_by_ECM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked once ECM has finished processing the document ( updated the ECM Id)</description>
        <label>Processed by ECM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <description>Reference Id : Lookup to the Content Version Id</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>254</length>
        <type>Text</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/classes/TestDataFactory_ECM.cls
@isTest
public class TestDataFactory_ECM {

    /**
    * @Description: Create File_Metadata__c
    * @Author:      Kejia Hu
    * @Date:        11/03/2020
    */
    public static File_Metadata__c createFileMetadata(String refId) {
        File_Metadata__c fMetadata = new File_Metadata__c();
        fMetadata.Reference_Id__c = refId;
        fMetadata.File_Mime_Type__c = 'ZIP';
        fMetadata.Count__c = 2;
        fMetadata.Processed_by_ECM__c = true;  
        fMetadata.File_Deleted__c = false;
        insert fMetadata;
        insert new ECM_Metadata__c(File_Metadata__c = fMetadata.Id);
        insert new ECM_Metadata__c(File_Metadata__c = fMetadata.Id);
        return fMetadata;
    }

    /**
    * @Description: Create ContentVersion
    * @Author:      Kejia Hu
    * @Date:        11/03/2020
    */
    public static ContentVersion createContentVersion() {
        ContentVersion contentVersionInsert = new ContentVersion(
            Title = 'Test',
            PathOnClient = 'Test.jpg',
            VersionData = Blob.valueOf('Test Content Data'),
            IsMajorVersion = true
        );
        insert contentVersionInsert;
        return contentVersionInsert;
    }

    /**
    * @Description: Create ContentDocumentLink
    * @Author:      Kejia Hu
    * @Date:        11/03/2020
    */
    public static ContentDocumentLink createContentDocumentLink(String parentId) {
        ContentVersion contentVersion = new ContentVersion(
                                                Title = 'Test CV',
                                                PathOnClient = 'cv.jpg',
                                                VersionData = Blob.valueOf('Test Content'),
                                                IsMajorVersion = true
                                                );
        insert contentVersion;    
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];

        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = parentId;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;
        return cdl;
    }
}