metadataPackage_1602884205764/objects/ECM_Processed__e.object
<CustomObject>
    <description>Once ECM completes creating the document. Fire this event with CMP Id and other attributes</description>
    <label>ECM Processed</label>
    <pluralLabel>ECM Processed</pluralLabel>
    <fields>
        <fullName>CMP_Id__c</fullName>
        <description>ECM document Id</description>
        <label>CMP_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <description>Mostly used for ZIP files</description>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Document_File_Extension__c</fullName>
        <label>Document File Extension</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_File_Size__c</fullName>
        <label>Document File Size</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LifeCycle_Status__c</fullName>
        <label>LifeCycle Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MessageId__c</fullName>
        <label>MessageId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFId__c</fullName>
        <description>Salesforce Id of processed documents</description>
        <label>SFId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the request. It could be Success or failure</description>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrackingId__c</fullName>
        <description>Tracking Id unique for every request</description>
        <label>TrackingId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/Handler_Processed__e.object
<CustomObject>
    <description>Once handler receives the request to create metadata and it informs salesforce with this event</description>
    <label>Handler Processed</label>
    <pluralLabel>Handler Processed</pluralLabel>
    <fields>
        <fullName>Count__c</fullName>
        <description>Count of files processed, Mainly used for zipped files</description>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LifeCycle_Status__c</fullName>
        <label>LifeCycle Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MessageId__c</fullName>
        <label>MessageId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFId__c</fullName>
        <description>Salesforce Id of the document processed</description>
        <label>SFId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the request</description>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrackingId__c</fullName>
        <description>The transaction or tracking Id linked with every request</description>
        <label>TrackingId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/classes/TestEventDataFactory.cls
@isTest
public class TestEventDataFactory {

    /**
    * @Description: Create ECM_Processed__e event
    * @Author:      Kejia Hu
    * @Date:        06/03/2020
    */
    public static ECM_Processed__e createECMProcessedEvent(String trackingId, String messageId, String sfId) { 
        return new ECM_Processed__e(
            CMP_Id__c = '93 3 ICM6 claims15 CLM_ClaimRecord59 26 A1001001A20C06B20146E0041618 A20C06B20146E004161 14 1085',
            Document_File_Size__c = '2460028',
            LifeCycle_Status__c = 'PASSED_ARCHIVED_DOCUMENT',
            Document_Name__c = 'Adhoc Communication',
            Count__c = 1.0,
            SFId__c = sfId,
            Document_File_Extension__c = 'docx',
            Status__c = 'SUCCESS',
            TrackingId__c = trackingId,
            MessageId__c = messageId
        );
    }

    /**
    * @Description: Create failed Handler_Processed__e event
    * @Author:      Kejia Hu
    * @Date:        06/03/2020
    */
    public static Handler_Processed__e createHandlerProcessedEventFailure(String trackingId, String sfId, String messageId) { 
        return new Handler_Processed__e(
            LifeCycle_Status__c = 'FAILED_SF_DOC_BINARY_RETRIEVAL',
            Count__c = 1.0,
            SFId__c = sfId,
            Status__c = 'FAILURE',
            TrackingId__c = trackingId,
            messageId__c = messageId
        );
    }

    /**
    * @Description: Create successed Handler_Processed__e event
    * @Author:      Kejia Hu
    * @Date:        06/03/2020
    */
    public static Handler_Processed__e createHandlerProcessedEventSuccess(String trackingId, String sfId, String messageId) { 
        return new Handler_Processed__e(
            LifeCycle_Status__c = 'SUCCEEDED_SF_DOC_BINARY_RETRIEVAL',
            Count__c = 1.0,
            SFId__c = sfId,
            Status__c = 'SUCCESS',
            TrackingId__c = trackingId,
            messageId__c = messageId
        );
    }

}