metadataPackage_1602884205764/objects/ECM_Metadata__c.object
<CustomObject>
    <label>ECM Metadata</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>ECM Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ECM Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>File_Metadata__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>File Metadata</label>
        <referenceTo>File_Metadata__c</referenceTo>
        <relationshipLabel>ECM Metadata</relationshipLabel>
        <relationshipName>ECM_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/File_Metadata__c.object
<CustomObject>
    <description>To store the metadata for the ECM files</description>
    <label>File Metadata</label>
    <nameField>
        <displayFormat>FM-{00000}</displayFormat>
        <label>File Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Meta_Junction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meta Junction</label>
        <referenceTo>Meta_Junction__c</referenceTo>
        <relationshipLabel>File Metadata</relationshipLabel>
        <relationshipName>File_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/Meta_Junction__c.object
<CustomObject>
    <description>To store the information link between email message and File Metadata</description>
    <label>Meta Junction</label>
    <nameField>
        <displayFormat>MJ-{00000}</displayFormat>
        <label>Meta Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meta Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadataPackage_1602884205764/classes/Omni_ECMMetadataFilesControllerTest.cls
/**
* @Description: Test class for Omni_ECMMetadataFilesController
* @Author:      Luis Merinero
* @Date:        08/04/2020
*/
@isTest
public class Omni_ECMMetadataFilesControllerTest {

	@isTest
    static void publishECMProcessed(){
        Case testCase = new Case();
        insert testCase;
        Meta_Junction__c metaJunction = new Meta_Junction__c();
        insert metaJunction;
        List<EmailMessage> messages = TestDataFactory.createEmailMessages(1, testCase, false);
        insert messages;
        File_Metadata__c fMetadata = TestDataFactory_ECM.createFileMetadata('testRef');
        fMetadata.Meta_Junction__c = metaJunction.Id;
        Update fMetadata;
        insert new ECM_Metadata__c(File_Metadata__c = fMetadata.Id);
        
        Test.startTest();
        Omni_ECMMetadataFilesController.getECMMetadataByEmailMessage(messages[0].id);
		messages[0].Meta_Junction__c = metaJunction.Id;
        update messages;
		List<ECM_Metadata__c> ecmList = Omni_ECMMetadataFilesController.getECMMetadataByEmailMessage(messages[0].id);
        Test.stopTest();
        
        System.assertEquals(ecmList.size(), 3);
    }
}