metadataPackage_1602884205764/objects/ECM_Metadata__c.object
<CustomObject>
    <label>ECM Metadata</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>ECM Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ECM Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>CMP_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CMP Id</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ECM_File_Mime_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ECM File Mime Type</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ECM_File_Size__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ECM File Size</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ECM__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ECM File Title</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Metadata__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>File Metadata</label>
        <referenceTo>File_Metadata__c</referenceTo>
        <relationshipLabel>ECM Metadata</relationshipLabel>
        <relationshipName>ECM_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Unique Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/ECM_Processed__e.object
<CustomObject>
    <description>Once ECM completes creating the document. Fire this event with CMP Id and other attributes</description>
    <label>ECM Processed</label>
    <pluralLabel>ECM Processed</pluralLabel>
    <fields>
        <fullName>CMP_Id__c</fullName>
        <description>ECM document Id</description>
        <label>CMP_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <description>Mostly used for ZIP files</description>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Document_File_Extension__c</fullName>
        <label>Document File Extension</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_File_Size__c</fullName>
        <label>Document File Size</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MessageId__c</fullName>
        <label>MessageId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFId__c</fullName>
        <description>Salesforce Id of processed documents</description>
        <label>SFId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the request. It could be Success or failure</description>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/ECMConfig__mdt.object
<CustomObject>
    <description>Configuration values for ECM related events</description>
    <label>ECM Config</label>
    <pluralLabel>ECM Configs</pluralLabel>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/File_Metadata__c.object
<CustomObject>
    <description>To store the metadata for the ECM files</description>
    <label>File Metadata</label>
    <nameField>
        <displayFormat>FM-{00000}</displayFormat>
        <label>File Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Count__c</fullName>
        <description>Count of files - Its always zero unless its a zip ( populated by the handler)</description>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MessageId__c</fullName>
        <description>Email Message SLF Id</description>
        <encryptionScheme>None</encryptionScheme>
        <label>MessageId</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processed_by_ECM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked once ECM has finished processing the document ( updated the ECM Id)</description>
        <label>Processed by ECM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <description>Reference Id : Lookup to the Content Version Id</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Unique Id</label>
        <length>254</length>
        <type>Text</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/classes/Omni_ECMProcessedPETriggerHandlerHelper.cls
/**
* @description Helper class for ECMProcessedPETriggerHandler
* @author      Vikas Sharma
* @date        13/01/2020                     
*/
public class Omni_ECMProcessedPETriggerHandlerHelper {

    /**
    * @description retrieve ECM related event config by name map
    * @author      Kejia Hu
    * @date        02/03/2020                     
    */
    public static final Map<String, String> ECM_CONFIG_BY_NAME {
        get {
            if(null == ECM_CONFIG_BY_NAME) {
                ECM_CONFIG_BY_NAME = new Map<String, String>();
                ECMConfig__mdt[] elementsForMappings = [
                    SELECT DeveloperName, Value__c FROM ECMConfig__mdt];
                for(ECMConfig__mdt element : elementsForMappings) {
                    ECM_CONFIG_BY_NAME.put(element.DeveloperName, element.Value__c);
                }
            }
            return ECM_CONFIG_BY_NAME;
        }
        set;
    }

/**
* @description Update the Flag on File Metadata
* 			   
* @author      Vikas Sharma
* @date        13/01/2020                     
*/
    public static void updateTheFlagForFileMetadata(Map<String, sObject> mapOfDocumentList)
    {
        List<File_Metadata__c> toUpsert = new List<File_Metadata__c>();
        List<ECM_Metadata__c> ECMtoUpsert = new List<ECM_Metadata__c>();
        
  		for (String currentId : mapOfDocumentList.keySet())
        {
            ECM_Processed__e handlerProcessedEvent = (ECM_Processed__e)mapOfDocumentList.get(currentId);
            if (handlerProcessedEvent.Status__c == 'SUCCESS')
            {
                String uniqueIdFileMetadata = handlerProcessedEvent.messageId__c + '-' + handlerProcessedEvent.SFId__c;
                toUpsert.add(new File_Metadata__c (Reference_Id__c = handlerProcessedEvent.SFId__c,
                                                   Unique_Id__c = uniqueIdFileMetadata,
                                                  	Processed_by_ECM__c = true, Count__c = handlerProcessedEvent.Count__c));
                ECMtoUpsert.add(new ECM_Metadata__c(
                							 ECM_File_Mime_Type__c = handlerProcessedEvent.Document_File_Extension__c,
                                             ECM_File_Size__c = handlerProcessedEvent.Document_File_Size__c,
                                             ECM__c = handlerProcessedEvent.Document_Name__c,
                                             File_Metadata__r = new File_Metadata__c(Unique_Id__c = uniqueIdFileMetadata), 
                    						 Unique_Id__c = handlerProcessedEvent.CMP_Id__c + uniqueIdFileMetadata,
                    						 CMP_Id__c = handlerProcessedEvent.CMP_Id__c));
            }
        }
        
        upsert toUpsert Unique_Id__c;
        upsert ECMtoUpsert Unique_Id__c;
    }
}