metadataPackage_1602884205764/objects/EmailMessage__e.object
<CustomObject>
    <description>Email message event to handle send email message logic</description>
    <label>Email Message</label>
    <pluralLabel>Email Messages</pluralLabel>
    <fields>
        <fullName>LogId__c</fullName>
        <description>Log Id that email log need to link to.</description>
        <label>Log Id</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReplyTo__c</fullName>
        <description>Email address for reply to in email message</description>
        <label>ReplyTo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TargetObjectId__c</fullName>
        <description>Contact Id for email.</description>
        <label>Target Object Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TemplateId__c</fullName>
        <label>Template Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TransactionId__c</fullName>
        <label>TransactionId</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WhatId__c</fullName>
        <description>Case that related to email message</description>
        <label>What Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/EmailMessageEventTriggerHandlerHelper.cls
/**
* @description helper class holds additional methods for trigger handler
* @author      Kejia Hu
* @date        04/11/2019                     
*/
public with sharing class EmailMessageEventTriggerHandlerHelper {
    
    /**
    * @description send multiple email messages asyn a time
    * @author      Kejia Hu
    * @date        04/11/2019                     
    */
    public static void sendEmailMessagesBulkAsyn(List<Omni_CommunicationDispatcher.Message> messagesToProcess) {
        List<Omni_CommunicationDispatcher.Message> messagesToSend = new List<Omni_CommunicationDispatcher.Message>();
        for (Integer i=0; i<messagesToProcess.size(); i++) {
            messagesToSend.add(messagesToProcess[0]);
            messagesToProcess.remove(0);
            if (i==Omni_ClaimNotificationConstant.NUM_EMAILS_TO_SEND_ASYN-1) {
                break;
            }
        }
        //Bulk email sending in queueable job
        System.enqueueJob(new Omni_EmailServiceAsync(JSON.serialize(messagesToSend), false, false));
        if (!messagesToProcess.isEmpty()) {
            sendEmailMessagesBulkAsyn(messagesToProcess);
        }
    }

    /**
    * @description generate Omni_CommunicationDispatcher.Message list from Email Message Event list, generate log per event
    * @author      Kejia Hu
    * @date        04/11/2019                     
    */
    public static List<Omni_CommunicationDispatcher.Message> generateCommMessagesFromEvents(List<EmailMessage__e> events) {
        List<Omni_CommunicationDispatcher.Message> messages = new List<Omni_CommunicationDispatcher.Message>();
        for (EmailMessage__e event : events) {
            Omni_CommunicationDispatcher.Message message = generateCommMessageFromEvent(event);
            messages.add(message);
        }
        return messages;
    }

    /**
    * @description generate Omni_CommunicationDispatcher.Message instance from one Email Message Event
    * @author      Kejia Hu
    * @date        04/11/2019                     
    */
    public static Omni_CommunicationDispatcher.Message generateCommMessageFromEvent(EmailMessage__e event) {
        Omni_CommunicationDispatcher.Message m = new Omni_CommunicationDispatcher.Message();
        m.targetObjectId = event.TargetObjectId__c;
        m.templateId = event.TemplateId__c;
        m.whatId = event.WhatId__c;
        m.replyTo = event.ReplyTo__c;
        m.transactionId = event.TransactionId__c;
        m.logId = event.LogId__c;
        return m;
    }
}