metadataPackage_1602884205764/objects/File_Metadata__c.object
<CustomObject>
    <description>To store the metadata for the ECM files</description>
    <label>File Metadata</label>
    <nameField>
        <displayFormat>FM-{00000}</displayFormat>
        <label>File Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>File_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked once file ( Content Document) is deleted from the salesforce - We are not deleting the metadata, only binary is deleted(Content Document)</description>
        <label>File Deleted</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/classes/BatchDeleteECMProcessedDocsTest.cls
@isTest
private class BatchDeleteECMProcessedDocsTest {

    @isTest
    static void testDeleteBatch() {
        ContentVersion cv = TestDataFactory_ECM.createContentVersion();
        File_Metadata__c filemetadata = TestDataFactory_ECM.createFileMetadata(cv.Id);
        System.assert([SELECT Id FROM File_Metadata__c WHERE File_Deleted__c = false].size() > 0);
        System.assert([SELECT Id FROM ContentVersion].size() > 0);
        Test.startTest();
		Omni_ECMFilesDeleteSchedule schedulableClass = new Omni_ECMFilesDeleteSchedule();
		schedulableClass.execute(null);
        Test.stopTest();
        System.assertEquals(true,[SELECT Id, File_Deleted__c FROM File_Metadata__c][0].File_Deleted__c, 'File Metadata should be updated as deleted');
        System.assertEquals(0, [SELECT Id FROM ContentVersion].size(),'ContentVersion should be deleted');
    } 
}