metadataPackage_1602884205764/objects/PolicyIssuingGroup__c.object
<CustomObject>
    <label>Policy Issuing Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>PolicyIssuingGroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Issuing Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>TypeCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>TypeCode</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/SurveyRequest__c.object
<CustomObject>
    <description>EOC Survey Requests, this object is used for failed EOC survey request re-sending</description>
    <label>Survey Request</label>
    <nameField>
        <displayFormat>SR-{0000000}</displayFormat>
        <label>Survey Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Key__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentLogId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Parent Log Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PolicyIssuingGroup__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Policy Issuing Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurveyIndicators__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Survey Indicators</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalLoss__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Total Loss</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/classes/Omni_SurveyRequest.cls
/**
* @Description Wrapper object for survey
* @Author      Kejia Hu
* @Date        11/02/2020
*/
public with sharing class Omni_SurveyRequest {

    public String key; //ClaimId or ExposureId
    public String type; // Claim or Exposure
    public String policyIssuingGroup;
    public String totalLoss;
    public String parentLogId;
    public List<String> surveyIndicators; // List of survey flag field API names

    public Omni_SurveyRequest(Omni_SurveyConfig surveyConfig) {
        this.key = surveyConfig.key;
        this.type = surveyConfig.type;
        this.parentLogId = surveyConfig.parentLogId;
        this.totalLoss = surveyConfig.claim.TotalLoss__c;
        this.policyIssuingGroup = Omni_ClaimEventDAOHelper.POLICY_ISSUING_GROUP_BY_ID.get(surveyConfig.claim.Policy_Issuing_Group__c).TypeCode__c;
        this.surveyIndicators = new List<String>(surveyConfig.surveyConfigByKey.keySet());
    }

    public Omni_SurveyRequest(SurveyRequest__c request) {
        this.key = request.Key__c;
        this.type = request.Type__c;
        this.parentLogId = request.ParentLogId__c;
        this.totalLoss = request.TotalLoss__c;
        this.policyIssuingGroup = request.PolicyIssuingGroup__c;
        this.surveyIndicators = request.SurveyIndicators__c.split(';');
    }
}