metadataPackage_1602884205764/objects/PolicyIssuingGroup__c.object
<CustomObject>
    <label>Policy Issuing Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>PolicyIssuingGroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Issuing Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadataPackage_1602884205764/objects/SurveyRequest__c.object
<CustomObject>
    <description>EOC Survey Requests, this object is used for failed EOC survey request re-sending</description>
    <label>Survey Request</label>
    <nameField>
        <displayFormat>SR-{0000000}</displayFormat>
        <label>Survey Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>JobId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Job Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job</label>
        <referenceTo>SurveyRequest__c</referenceTo>
        <relationshipLabel>SurveyRequests</relationshipLabel>
        <relationshipName>SurveyRequestsPerJob</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentLogId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Parent Log Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PolicyIssuingGroup__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Policy Issuing Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurveyIndicators__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Survey Indicators</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalLoss__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Total Loss</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>SurveyJob</fullName>
        <active>true</active>
        <label>Survey Job</label>
    </recordTypes>
</CustomObject>

metadataPackage_1602884205764/classes/Omni_EOCSurveyRequestBatch.cls
/**
* @description batch job to retry failed survey request jobs
* @author      Kejia Hu
* @date        19/05/2020                     
*/
public class Omni_EOCSurveyRequestBatch implements Database.Batchable<sobject> {
    
    public String queryString;
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        queryString = 'SELECT Id, JobId__c,'
                      +   ' (SELECT Id, Key__c, ParentLogId__c, PolicyIssuingGroup__c, SurveyIndicators__c, TotalLoss__c, Type__c FROM SurveyRequestsPerJob__r)'
                      + ' FROM SurveyRequest__c'
                      + ' WHERE RecordType.DeveloperName = \'SurveyJob\'';
        return Database.getQueryLocator(queryString);
    }
    
    public void execute(Database.BatchableContext bc, List<SurveyRequest__c> scope) {
        try {
            if (scope != null && !scope.isEmpty()) {
                List<SurveyRequest__c> toDelete = new List<SurveyRequest__c>();
                for (SurveyRequest__c requestJob : scope) {
                    Map<String, Omni_SurveyRequest> surveyRequestByKey = new Map<String, Omni_SurveyRequest>();
                    for (SurveyRequest__c request : requestJob.SurveyRequestsPerJob__r) {
                        surveyRequestByKey.put(request.Key__c, new Omni_SurveyRequest(request));
                    }
                    if (!surveyRequestByKey.isEmpty()) {
                        System.enqueueJob(new Omni_EOCSurveyRequest(surveyRequestByKey));
                    }
                    toDelete.addAll(requestJob.SurveyRequestsPerJob__r);
                }
                toDelete.addAll(scope);
                delete toDelete;
            }
        } catch(Exception e) {
            System.debug(e.getMessage() + ' ' + e.getStackTraceString());
            ApplicationLogHandler.saveExceptionLog('EOCSurveyRequestBatch', e, null);
        }
    }
    
    public void finish(Database.BatchableContext bc){}

}