metadataPackage_1602884205764/objects/Pulse_Survey_Result__c.object
<CustomObject>
    <label>Pulse Survey Result</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Purse Survey Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pulse Survey Results</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Purse_Survey_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Responded__c</fullName>
        <defaultValue>false</defaultValue>
        <description>boolean flag to check wether survey has a response</description>
        <label>Responded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey_URL_DateTime__c</fullName>
        <description>each survey link has a date appended to stop users from clikcing on one survey link multiple times</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Survey URL DateTime</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/classes/Omni_PulseSurveyResultSelector.cls
/**
* @Description: Selctor for Task PulseSurveyResult__c
* @Author:      Damian Kazior
* @Date:        05/01/2020
*/
public without sharing class Omni_PulseSurveyResultSelector {

    /**
    * @Description: Selctor for User sObject
    * @Author:      Damian Kazior
    * @Date:        05/01/2020
    */
    public static List<Pulse_Survey_Result__c> getSurveyResultsByTimestampAndCaseId(String timestamp, String caseId) {
        return  [SELECT ID, Case__c, Responded__c
                FROM Pulse_Survey_Result__c 
                WHERE Case__c =:caseId AND Survey_URL_DateTime__c=:timestamp];            
    }

}