metadataPackage_1602884205764/objects/Template_Management_Config__mdt.object
<CustomObject>
    <description>Setup for template management</description>
    <label>Template Management Config</label>
    <pluralLabel>Template Management Configs</pluralLabel>
    <fields>
        <fullName>Cloned_Emails_Folder_Name__c</fullName>
        <description>API name of the folder accessible by template submitter which stores copies of email temaplates</description>
        <label>Cloned Emails Folder Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Letterhead_name__c</fullName>
        <description>API name of letterhead which will be applied to all templates created by template submitter</description>
        <label>Letterhead name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Style__c</fullName>
        <description>Style for all templates created by template submitter</description>
        <label>Template Style</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Type__c</fullName>
        <description>Template type (HTML or VF) for all templates created by template submitter</description>
        <label>Template Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

metadataPackage_1602884205764/objects/Template_Request__c.object
<CustomObject>
    <description>Store all request for changes to email templates. Object stores template that agent wants to change and once change gets approved, email template gets updated</description>
    <label>Template Request</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Template Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Template Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Email_Template_Name__c</fullName>
        <description>Name of email template that needs to be changed (facilitates the approver&apos;s job in finding correct template in folder)</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Email Template Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/Omni_Aura_TemplateRequestController.cls
/**
   * @Description: Controller for Aura components creating and modifying Email Requests
   * @Author:      Damian Kazior, PwC
   * @Date:        25/06/2019
*/
public with sharing class Omni_Aura_TemplateRequestController { 

    /**
    * @Description: Fetch all email templates from folder accessible by template manager. Store templates in cache for better performance
    * @Author:      Damian Kazior, PwC
    * @Date:        25/06/2019
    */
    @AuraEnabled(cacheable=true)
    public static Map<String, String> getEmailTemplates() {

        Map<String, String> pickListValuesMap = new Map<String, String>();
        Template_Management_Config__mdt templateConfiguration = Utility.getTemplateManagementConfigurations();
        List<EmailTemplate> templates = Omni_EmailTemplateSelector.getAllEmailTemplatesByFolderName(templateConfiguration.Cloned_Emails_Folder_Name__c);
       
        for(EmailTemplate template : templates){
            pickListValuesMap.put(template.Id, template.Name); 
        }     
        return pickListValuesMap;
    }

    /**
    * @Description: When user requests to create new email template, create that template in accessible folder and persist template request
                    with appropiate temlate
    * @Author:      Damian Kazior, PwC
    * @Date:        25/06/2019
    */
    @AuraEnabled
    public static Omni_AuraResponse createNewEmailTemplate(Template_Request__c templateRequest) {
        Omni_AuraResponse auraResponse = new Omni_AuraResponse(); 
        auraResponse.success = true;
        EmailTemplate newTemplate;

        try{
            Template_Management_Config__mdt templateConfiguration = Utility.getTemplateManagementConfigurations();
            BrandTemplate letterHead                              = Omni_BrandTemplateSelector.getBrandTemplatesByName(templateConfiguration.Letterhead_name__c);
            Folder folder                                         = Omni_FolderSelector.getFolderByName(templateConfiguration.Cloned_Emails_Folder_Name__c);
            
            newTemplate = new EmailTemplate(
                BrandTemplateId = letterHead.Id,
                DeveloperName   = templateRequest.Email_Template_Name__c,
                FolderId        = folder.id,
                Name            = templateRequest.Email_Template_Name__c, 
                TemplateStyle   = templateConfiguration.Template_Style__c,
                TemplateType    = templateConfiguration.Template_Type__c
            );
            insert newTemplate;
            auraResponse.data = newTemplate;
        }catch(Exception e){
            ApplicationLogHandler.addExceptionLog('Omni_Aura_TemplateRequestController', e, null);
            auraResponse.success = false;
            auraResponse.message = Label.Omni_ActionOverride_NewTemplateRequest_TemplateCannotBeCreated;
        }
        return auraResponse;
    }
}